# Generated by Django 5.1.6 on 2026-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctwa", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ctwacampaign",
            new_name="ctwa_ctwaca_tenant__87dd43_idx",
            old_name="ctwa_campaign_tenant_status",
        ),
        migrations.RenameIndex(
            model_name="ctwacampaign",
            new_name="ctwa_ctwaca_meta_ad_d652ef_idx",
            old_name="ctwa_campaign_meta_ad_id_idx",
        ),
        migrations.RenameIndex(
            model_name="ctwalead",
            new_name="ctwa_ctwale_tenant__25df62_idx",
            old_name="ctwa_lead_t_camp_status_idx",
        ),
        migrations.RenameIndex(
            model_name="ctwalead",
            new_name="ctwa_ctwale_meta_ad_75e36c_idx",
            old_name="ctwa_lead_meta_ad_id_idx",
        ),
        migrations.RenameIndex(
            model_name="ctwalead",
            new_name="ctwa_ctwale_ctwa_cl_00e550_idx",
            old_name="ctwa_lead_clid_idx",
        ),
        migrations.RenameIndex(
            model_name="ctwalead",
            new_name="ctwa_ctwale_flagged_3ae9a7_idx",
            old_name="ctwa_lead_orphan_idx",
        ),
        migrations.AddField(
            model_name="ctwacampaign",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ctwacampaign",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ctwalead",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ctwalead",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="ctwacampaign",
            name="budget_amount_minor",
            field=models.BigIntegerField(default=0, help_text="In smallest currency unit (paise/cents)."),
        ),
        migrations.AlterField(
            model_name="ctwacampaign",
            name="budget_type",
            field=models.CharField(
                choices=[("daily", "Daily"), ("lifetime", "Lifetime")], default="daily", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="ctwacampaign",
            name="prefilled_message",
            field=models.TextField(
                help_text="Text WhatsApp auto-fills when a user taps the ad. Validated against Meta's denylist + length limit by ads/services/validators.py."
            ),
        ),
        migrations.AlterField(
            model_name="ctwacampaign",
            name="qualification_signal",
            field=models.CharField(
                choices=[
                    ("flow_node", "Flow node sets qualified=True"),
                    ("agent_claim", "Agent claims conversation"),
                    ("message_count", "After N inbound messages"),
                ],
                default="flow_node",
                help_text="When to fire the Meta Conversions API Lead event. NEVER on first inbound message — that's the #1 CAPI mistake. Default flow_node means a flow explicitly marks the lead qualified.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ctwacampaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review (Meta)"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("disapproved", "Disapproved by Meta"),
                    ("archived", "Archived"),
                    ("external", "Shadow campaign (created from orphan reconciliation)"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ctwalead",
            name="qualification_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("engaged", "Engaged"),
                    ("qualified", "Qualified"),
                    ("disqualified", "Disqualified"),
                    ("converted", "Converted"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
