# Generated by Django 5.1.6 on 2026-05-19 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_adcreative_is_active_audiencetemplate_description_and_more"),
        ("chat_flow", "0008_chatflow_triggers"),
        ("ctwa", "0002_rename_ctwa_campaign_tenant_status_ctwa_ctwaca_tenant__87dd43_idx_and_more"),
        ("meta", "0002_rename_meta_conn_t_reauth_idx_meta_metabu_tenant__eee1da_idx_and_more"),
        ("tenants", "0019_rbac_add_voice_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ctwalead",
            name="last_crm_external_event_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddConstraint(
            model_name="ctwacampaign",
            constraint=models.UniqueConstraint(
                condition=models.Q(("meta_ad_id", ""), _negated=True),
                fields=("tenant", "meta_ad_id"),
                name="ctwa_campaign_unique_meta_ad_id_per_tenant",
            ),
        ),
    ]
