# Generated by Django 5.1.6 on 2026-02-08 10:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None)),
                ('first_name', models.CharField(blank=True, help_text='Contact first name', max_length=255)),
                ('last_name', models.CharField(blank=True, help_text='Contact last name', max_length=255)),
                ('tag', models.CharField(blank=True, help_text='Tag for the contact', max_length=255)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram')], default='MANUAL', max_length=20)),
                ('assigned_to_type', models.CharField(choices=[('USER', 'User'), ('BOT', 'Bot'), ('CHATFLOW', 'ChatFlow'), ('UNASSIGNED', 'Unassigned')], db_index=True, default='UNASSIGNED', max_length=15)),
                ('assigned_to_id', models.PositiveIntegerField(blank=True, help_text='User ID or Bot ID depending on assigned_to_type', null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by_type', models.CharField(blank=True, choices=[('USER', 'User'), ('BOT', 'Bot'), ('CHATFLOW', 'ChatFlow'), ('UNASSIGNED', 'Unassigned')], help_text='Type of actor who made the assignment', max_length=15, null=True)),
                ('assigned_by_id', models.PositiveIntegerField(blank=True, help_text='User ID, Bot ID, or ChatFlow ID depending on assigned_by_type', null=True)),
                ('assignment_note', models.TextField(blank=True, help_text='Note or instructions from assigner to assignee', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', help_text='Whether this conversation is open or closed', max_length=10)),
            ],
            options={
                'verbose_name': 'Tenant Contact',
                'verbose_name_plural': 'Tenant Contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
