# Generated by Django 5.1.6 on 2026-02-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantcontact",
            name="dnc",
            field=models.BooleanField(default=False, help_text="Do Not Call flag"),
        ),
        migrations.AddField(
            model_name="tenantcontact",
            name="last_called_at",
            field=models.DateTimeField(blank=True, help_text="When this contact was last called", null=True),
        ),
        migrations.AddField(
            model_name="tenantcontact",
            name="lead_score",
            field=models.PositiveSmallIntegerField(default=0, help_text="Lead score (0-100)"),
        ),
        migrations.AddField(
            model_name="tenantcontact",
            name="lead_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "New"),
                    ("CONTACTED", "Contacted"),
                    ("QUALIFIED_LEAD", "Qualified Lead"),
                    ("INTERESTED", "Interested"),
                    ("NOT_INTERESTED", "Not Interested"),
                    ("APPOINTMENT_SET", "Appointment Set"),
                    ("SALE_CLOSED", "Sale Closed"),
                    ("DO_NOT_CONTACT", "Do Not Contact"),
                ],
                help_text="Lead qualification status",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenantcontact",
            name="preferred_channel",
            field=models.CharField(
                blank=True,
                choices=[("WA", "WhatsApp"), ("VOICE", "Voice"), ("SMS", "SMS"), ("EMAIL", "Email")],
                help_text="Preferred communication channel",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenantcontact",
            name="total_calls",
            field=models.PositiveIntegerField(default=0, help_text="Total number of calls with this contact"),
        ),
        migrations.AlterField(
            model_name="tenantcontact",
            name="source",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("WHATSAPP", "WhatsApp"), ("TELEGRAM", "Telegram"), ("VOICE", "Voice")],
                default="MANUAL",
                max_length=20,
            ),
        ),
    ]
