# Generated by Django 5.1.15 on 2026-04-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0009_importjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantcontact",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("WHATSAPP", "WhatsApp"),
                    ("TELEGRAM", "Telegram"),
                    ("VOICE", "Voice"),
                    ("SMS", "SMS"),
                    ("RCS", "RCS"),
                    ("IMPORT", "Import"),
                ],
                default="MANUAL",
                max_length=20,
            ),
        ),
    ]
