# Generated by Django 5.2.16 on 2026-09-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_mobile_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="The password was set by an operator and must be replaced before the account can be used.",
            ),
        ),
    ]
