# Generated by Django 5.2.16 on 2026-09-12 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0027_tenant_access_key_hashed"),
        ("users", "0003_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpersonationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        help_text="Username of the real user at the time the session started — kept if the account is deleted.",
                        max_length=150,
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the organisation at the time the session started.",
                        max_length=255,
                    ),
                ),
                (
                    "token_jti",
                    models.CharField(
                        db_index=True,
                        help_text="JTI of the issued access token. One row per token, so a session is never ambiguous.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the issued token expires on its own."),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the session was exited, if it was exited before expiry.",
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The real platform user who started the session.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impersonation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organisation that was viewed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impersonation_sessions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impersonation Session",
                "verbose_name_plural": "Impersonation Sessions",
                "ordering": ["-started_at"],
            },
        ),
    ]
