# Generated by Django 5.2.16 on 2026-09-13 18:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_mobile_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAdminChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[("granted", "Granted"), ("revoked", "Revoked")], db_index=True, max_length=16
                    ),
                ),
                (
                    "subject_username",
                    models.CharField(
                        help_text="Username of the subject at the time — kept if the account is deleted.",
                        max_length=150,
                    ),
                ),
                (
                    "subject_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of the subject at the time. The invite names an address, so the address is the record.",
                        max_length=254,
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        help_text="Username of the actor at the time — kept if the account is deleted.", max_length=150
                    ),
                ),
                ("changed_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The platform administrator who made the change.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_admin_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user whose platform administration was granted or revoked.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_admin_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Administration Change",
                "verbose_name_plural": "Platform Administration Changes",
                "ordering": ["-changed_at", "-id"],
            },
        ),
    ]
