# Generated by Django 5.1.6 on 2026-04-14 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcast', '0004_url_tracking_models'),
        ('contacts', '0006_alter_tenantcontact_source'),
        ('team_inbox', '0003_alter_messages_platform'),
        ('tenants', '0015_alter_tenantmedia_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('TWILIO', 'Twilio'), ('MSG91', 'MSG91'), ('FAST2SMS', 'Fast2SMS')], default='TWILIO', max_length=20)),
                ('provider_credentials', models.JSONField(blank=True, help_text='Provider credentials (API keys, auth tokens). Keep encrypted at rest in production.', null=True)),
                ('sender_id', models.CharField(help_text='Sender ID, short code, or sending number', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_limit', models.IntegerField(default=10000)),
                ('messages_sent_today', models.IntegerField(default=0)),
                ('webhook_secret', models.CharField(blank=True, max_length=64, unique=True)),
                ('webhook_url', models.URLField(blank=True, max_length=512)),
                ('dlr_webhook_url', models.URLField(blank=True, max_length=512)),
                ('dlt_entity_id', models.CharField(blank=True, max_length=30, null=True)),
                ('dlt_template_id', models.CharField(blank=True, max_length=30, null=True)),
                ('price_per_sms', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('price_per_sms_international', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_apps', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'SMS App',
                'verbose_name_plural': 'SMS Apps',
                'unique_together': {('tenant', 'provider', 'sender_id')},
            },
        ),
        migrations.CreateModel(
            name='SMSOutboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_number', models.CharField(max_length=32)),
                ('from_number', models.CharField(blank=True, max_length=32)),
                ('message_text', models.TextField()),
                ('segment_count', models.IntegerField(default=1)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('UNDELIVERED', 'Undelivered')], default='PENDING', max_length=20)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('provider_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcast_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_outbound_messages', to='broadcast.broadcastmessage')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='contacts.tenantcontact')),
                ('inbox_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_outbound_messages', to='team_inbox.messages')),
                ('sms_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='sms.smsapp')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSWebhookEvent',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INBOUND', 'Inbound'), ('DLR', 'Delivery Report'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('provider', models.CharField(choices=[('TWILIO', 'Twilio'), ('MSG91', 'MSG91'), ('FAST2SMS', 'Fast2SMS')], max_length=20)),
                ('from_number', models.CharField(blank=True, max_length=32)),
                ('to_number', models.CharField(blank=True, max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('retry_count', models.IntegerField(default=0)),
                ('sms_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='sms.smsapp')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['sms_app', 'provider_message_id'], name='sms_smswebh_sms_app_99ca91_idx'), models.Index(fields=['is_processed', 'created_at'], name='sms_smswebh_is_proc_f28ec6_idx')],
                'unique_together': {('sms_app', 'provider_message_id', 'event_type')},
            },
        ),
    ]
