# Generated by Django 5.1.6 on 2026-04-14 10:51

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsapp",
            name="provider_credentials",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                help_text="Provider credentials (API keys, auth tokens) stored as an encrypted JSON string.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="smsoutboundmessage",
            name="provider_message_id",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
