# Generated by Django 5.1.15 on 2026-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0003_smsapp_fallback_app_smsoutbound_provider_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsoutboundmessage",
            name="provider_used",
            field=models.CharField(
                blank=True,
                choices=[("TWILIO", "Twilio"), ("MSG91", "MSG91"), ("FAST2SMS", "Fast2SMS")],
                help_text="Provider that actually sent this message (may differ from sms_app.provider after failover)",
                max_length=20,
            ),
        ),
    ]
