# Generated by Django 5.1.6 on 2026-02-09 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import team_inbox.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0002_initial"),
        ("tenants", "0003_tenantwaapp_bsp_credentials_tenantwaapp_daily_limit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageEventIds",
            fields=[
                (
                    "numbering",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
            ],
            options={
                "verbose_name": "Message/Event ID",
                "verbose_name_plural": "Message/Event IDs",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TICKET_ASSIGNED", "Ticket Assigned"),
                            ("TICKET_UNASSIGNED", "Ticket Unassigned"),
                            ("TICKET_REASSIGNED", "Ticket Reassigned"),
                            ("TICKET_OPENED", "Ticket Opened"),
                            ("TICKET_CLOSED", "Ticket Closed"),
                            ("TICKET_REOPENED", "Ticket Reopened"),
                            ("SYSTEM", "System Event"),
                            ("CUSTOM", "Custom Event"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("note", models.TextField(blank=True, help_text="Note or instructions for the assignment", null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        choices=[("USER", "User"), ("BOT", "Bot"), ("CHATFLOW", "ChatFlow")],
                        default="USER",
                        max_length=10,
                    ),
                ),
                ("created_by_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "assigned_by_type",
                    models.CharField(
                        blank=True,
                        choices=[("USER", "User"), ("BOT", "Bot"), ("CHATFLOW", "ChatFlow")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("assigned_by_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "assigned_to_type",
                    models.CharField(
                        blank=True,
                        choices=[("USER", "User"), ("BOT", "Bot"), ("CHATFLOW", "ChatFlow")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("assigned_to_id", models.PositiveIntegerField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, help_text="Icon name or emoji", max_length=50, null=True)),
                (
                    "color_background",
                    models.CharField(blank=True, help_text="Background color hex code", max_length=20, null=True),
                ),
                ("color_text", models.CharField(blank=True, help_text="Text color hex code", max_length=20, null=True)),
                (
                    "event_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Type-specific event data (reason, resolution_notes, etc.)"
                    ),
                ),
                (
                    "assigned_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who assigned (if actor is USER)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_assigned_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to (if actor is USER)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_assigned_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="contacts.tenantcontact"
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the event (if actor is USER)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="tenants.tenant"
                    ),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="team_inbox.messageeventids",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("content", models.JSONField(validators=[team_inbox.validators.validate_message_content])),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "direction",
                    models.CharField(choices=[("INCOMING", "Incoming"), ("OUTGOING", "Outgoing")], max_length=10),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("WHATSAPP", "WhatsApp"), ("TELEGRAM", "Telegram"), ("SMS", "SMS")], max_length=10
                    ),
                ),
                (
                    "author",
                    models.CharField(choices=[("USER", "User"), ("CONTACT", "Contact"), ("BOT", "Bot")], max_length=10),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External message ID (gs_id) for status tracking via BroadcastMessage lookup",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="contacts.tenantcontact",
                    ),
                ),
                (
                    "message_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="team_inbox.messageeventids",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
