# Generated by Django 5.1.6 on 2026-02-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_inbox", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="platform",
            field=models.CharField(
                choices=[("WHATSAPP", "WhatsApp"), ("TELEGRAM", "Telegram"), ("SMS", "SMS"), ("VOICE", "Voice")],
                max_length=10,
            ),
        ),
    ]
