# Generated by Django 5.1.15 on 2026-04-17 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team_inbox", "0006_conversation_messages_conversation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="team_inbox__tenant__ef00a5_idx",
            old_name="team_inbox_conv_tenant_contact",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="team_inbox__tenant__89b2f7_idx",
            old_name="team_inbox_conv_tenant_active",
        ),
    ]
