# Generated by Django 5.1.6 on 2026-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_inbox", "0010_message_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetag",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagetag",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="messagetag",
            name="auto",
            field=models.BooleanField(default=False, help_text="True when applied by ingestion automation."),
        ),
        migrations.AlterField(
            model_name="messagetag",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
