"""
Django settings for jina_connect project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import tempfile
import warnings
from datetime import timedelta
from pathlib import Path

from decouple import Config, RepositoryEnv
from decouple import config as _auto_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ── Which .env is actually read ──────────────────────────────────────────────
# python-decouple's AutoConfig searches upward from the module that calls
# config() — this file — so it finds jina_connect/.env before the project-root
# .env. On one deployment both existed, the root file had ten keys, and it was
# ignored in its entirety. The failure surfaced as a confusing
# "FIELD_ENCRYPTION_KEY defined incorrectly" rather than "wrong file".
#
# The precedence below is the same one AutoConfig already applied, made
# explicit so it can be read rather than inferred. Deployments keep working
# unchanged; what is new is that a shadowed root .env now says so out loud
# instead of failing obscurely later.
_APP_ENV = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
_ROOT_ENV = os.path.join(BASE_DIR, ".env")

if os.path.isfile(_APP_ENV):
    config = Config(RepositoryEnv(_APP_ENV))
    ACTIVE_ENV_FILE = _APP_ENV
    if os.path.isfile(_ROOT_ENV):
        warnings.warn(
            f"Two .env files are present. Reading {_APP_ENV} and IGNORING {_ROOT_ENV} — "
            f"edits to the root file will have no effect. Keep one.",
            RuntimeWarning,
            stacklevel=2,
        )
elif os.path.isfile(_ROOT_ENV):
    config = Config(RepositoryEnv(_ROOT_ENV))
    ACTIVE_ENV_FILE = _ROOT_ENV
else:
    # No file at all: fall back to environment variables only, which is how
    # CI and container deployments supply configuration.
    config = _auto_config
    ACTIVE_ENV_FILE = None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", "change-me-in-production")

# Encryption key for django-encrypted-model-fields
# In production, set FIELD_ENCRYPTION_KEY env var to a proper Fernet key.
FIELD_ENCRYPTION_KEY = config(
    "FIELD_ENCRYPTION_KEY",
    default="",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", False, cast=bool)

# ---------------------------------------------------------------------------
# Security settings (satisfy `manage.py check --deploy`)
# In production behind a reverse proxy / load balancer, set these via env vars.
# ---------------------------------------------------------------------------
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", 0, cast=int)
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", False, cast=bool)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", not DEBUG, cast=bool)

# Behind a TLS-terminating proxy (ALB / Nginx / Cloudflare), trust the
# ``X-Forwarded-Proto`` header so ``request.scheme`` /
# ``request.is_secure()`` return ``https`` and webhook signature
# verification reconstructs URLs the providers actually signed.
# Disabled in dev (``DEBUG=True``) so a local ngrok tunnel without the
# header still works.
if not DEBUG and config("TRUST_X_FORWARDED_PROTO", True, cast=bool):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Silence deploy-check warnings that are infrastructure concerns (handled by
# the reverse proxy / load balancer in production, not Django itself).
SILENCED_SYSTEM_CHECKS = [
    "security.W004",  # SECURE_HSTS_SECONDS — set at LB / Nginx level
    "security.W008",  # SECURE_SSL_REDIRECT — handled by LB / Nginx
    "security.W009",  # SECRET_KEY strength — CI uses placeholder; real key in prod .env
    "security.W012",  # SESSION_COOKIE_SECURE — set via env in production
    "security.W016",  # CSRF_COOKIE_SECURE — set via env in production
    "security.W018",  # DEBUG should be False — CI runs with DEBUG=False already
]

ALLOWED_HOSTS = ["*"]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
    # "DELETE",
]

CORS_ALLOW_HEADERS = [
    "Accept",
    "Accept-Encoding",
    "Authorization",
    "Content-Type",
    "ngrok-skip-browser-warning",  # Add your custom header here
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "channels",
    "django_crontab",
    "django_celery_results",
    "corsheaders",
    "drf_yasg",
    "django_filters",
    "djmoney.contrib.exchange",
    "users",
    "tenants",
    "phonenumber_field",
    "simple_history",
    "wa",
    "razorpay",
    "transaction",
    "chat_flow",
    "broadcast",
    "contacts",
    "message_templates",
    "team_inbox",
    "notifications",
    "telegram",
    "sms",
    "rcs",
    "voice",
    # ── CTWA initiative (#187) ──────────────────────────────────────────
    "meta",  # #191 — Meta Business Login + system-user token store
    "ads",  # #196 — Meta Marketing API client + creative/audience + BUC limiter
    "ctwa",  # #194 — CTWA campaign + lead + ingestion
    "attribution",  # #197 — Meta Conversions API push (CAPI)
    "crm",  # #198 — HubSpot / Salesforce / generic-webhook connectors
    "availability",  # Cl. 5.4 — SLA availability record and monthly report
    # ──────────────────────────────────────────────────────────────────
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
]

# ── Django Silk (visual request profiler) ── only in DEBUG mode ──
if DEBUG:
    INSTALLED_APPS += ["silk"]
    SILKY_PYTHON_PROFILER = True  # cProfile per request
    SILKY_PYTHON_PROFILER_BINARY = True  # downloadable .prof files
    SILKY_MAX_RECORDED_REQUESTS = 5_000  # auto-purge after this many
    SILKY_MAX_RECORDED_REQUESTS_CHECK_PERCENT = 10
    SILKY_META = True  # adds silk overhead info

    # Where the binary profiles go. django-silk defaults this to MEDIA_ROOT,
    # which put profiler output in the uploads directory — and served it,
    # since nginx aliases /media/. SILKY_MAX_RECORDED_REQUESTS purges silk's
    # database rows but never the files, so they accumulated without bound:
    # 65,613 files and 7.2 GB on one box before anyone looked.
    #
    # Profiles are disposable debug artefacts, so they belong in a temp
    # directory, not beside user data and not inside the code tree.
    SILKY_PYTHON_PROFILER_RESULT_PATH = config(
        "SILKY_PYTHON_PROFILER_RESULT_PATH",
        os.path.join(tempfile.gettempdir(), "jina-connect-silk"),
    )
    os.makedirs(SILKY_PYTHON_PROFILER_RESULT_PATH, exist_ok=True)

# CSRF_TRUSTED_ORIGINS = [
#     "*"
# ]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

# Silk middleware — injected only in DEBUG mode
if DEBUG:
    MIDDLEWARE += ["silk.middleware.SilkyMiddleware"]

CSRF_COOKIE_SECURE = False

ROOT_URLCONF = "jina_connect.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "jina_connect.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": config("DB_NAME", "jc6"),
        "USER": config("DB_USER", "postgres"),
        "PASSWORD": config("DB_PASSWORD", "postgres"),
        "TEST": {
            "NAME": "test_server",
        },
        "HOST": config("DB_HOST", "localhost"),
        "PORT": 5432,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_USE_JWT = True


DEFAULT_RENDERER_CLASSES = (
    "rest_framework.renderers.JSONRenderer",
    "rest_framework.renderers.BrowsableAPIRenderer",
    "rest_framework_csv.renderers.PaginatedCSVRenderer",
)
REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "2000/day",
        "anon": "2000/day",
        "waba_sync": "2/minute",  # 1 call per 30 seconds
    },
    "DEFAULT_RENDERER_CLASSES": DEFAULT_RENDERER_CLASSES,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "PAGE_SIZE_QUERY_PARAM": "page_size",
    # DRF 3.17 removed rest_framework.schemas.coreapi entirely. The CoreAPI
    # schema class was vestigial here anyway: drf-yasg generates its own schema
    # and does not require it, and coreapi was never an installed dependency.
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.BasicAuthentication",
        "jina_connect.authentication.jwt.CustomJWTAuthentication",
    ),
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    "COERCE_DECIMAL_TO_STRING": False,
}

# Allow large POST payloads (e.g. charge breakdown with 500k contact_ids)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 600000

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=config("ACCESS_TOKEN_LIFETIME", 90, cast=int)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=180),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(days=90),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=90),
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Per-deployment locale. These are env-driven because the platform is
# white-labelled and deployments do not all sit in the same country as the
# default. Defaults preserve the existing behaviour.
#
# TIME_ZONE is not cosmetic. Both contractual reports — the Cl. 4.2 Active
# Account Report and the Cl. 5.4 availability report — compute their periods
# in local time, so this decides which month an event is billed in.
LANGUAGE_CODE = config("LANGUAGE_CODE", "en-us")

TIME_ZONE = config("TIME_ZONE", "Asia/Kolkata")

# USE_I18N = True

USE_TZ = True

# Assumed country for phone numbers entered in national rather than E.164
# format. Set per deployment so local numbers validate.
PHONENUMBER_DEFAULT_REGION = config("PHONENUMBER_DEFAULT_REGION", "IN")

# ── Platform currency ────────────────────────────────────────────────────────
# One currency per deployment, set at provisioning and changed almost never.
# It lives here rather than in the database deliberately: it is deployment
# configuration, and keeping it out of the database means no UI can edit it.
#
# Changing this does NOT convert existing rows. Use the set_platform_currency
# management command, which reports what it would touch and refuses to run
# once transactions exist unless forced.
PLATFORM_DEFAULT_CURRENCY = config("PLATFORM_DEFAULT_CURRENCY", "USD")

# Bound django-money's choice list. Left unset it offers the whole of
# ISO 4217 — about 300 entries including obsolete currencies — wherever it
# renders a choice field. A short list is fewer ways to pick something the
# payment provider cannot settle.
CURRENCIES = ("USD", "INR", "EUR", "GBP", "AED", "SGD", "AUD", "ZAR")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Product name used when BrandingSettings.product_name is blank.
# White-label deployments override this via env.
DEFAULT_PRODUCT_NAME = config("DEFAULT_PRODUCT_NAME", "Jina Connect")

# Primary brand colour used when BrandingSettings.primary_color is blank.
# Matches --color-brand-500 in the web app's default palette.
DEFAULT_BRAND_COLOR = config("DEFAULT_BRAND_COLOR", "#465fff")

# --- Partner reporting (partner agreement Cl. 4.2 / 5.4) ---------------------
# PLACEHOLDERS. Set PARTNER_NAME and PARTNER_REPORT_RECIPIENTS per deployment
# before the first report goes out; the defaults deliberately do not point at a
# real mailbox so an unconfigured deployment cannot silently email a stranger.
# Contractual availability commitment, as a percentage (Cl. 5.4).
AVAILABILITY_COMMITMENT_PERCENT = config("AVAILABILITY_COMMITMENT_PERCENT", "99.5")

# --- Synthetic monitoring (the instrument behind the Cl. 5.4 figure) ---------
# Grafana Cloud Synthetic Monitoring probes the platform; the nightly
# `aggregate_availability` command copies its counts into DailyAvailability,
# because Grafana's free tier retains metrics for 14 days and a calendar-month
# report needs 31. Unset here on purpose: a deployment with no credentials must
# record no availability rather than invent them. See availability/README.md.
GRAFANA_PROM_URL = config("GRAFANA_PROM_URL", "")
GRAFANA_PROM_USER = config("GRAFANA_PROM_USER", "")
GRAFANA_PROM_TOKEN = config("GRAFANA_PROM_TOKEN", "")

# Must match the interval the synthetic checks actually run at: a failed check
# is counted as exactly this much downtime.
AVAILABILITY_PROBE_INTERVAL_SECONDS = config("AVAILABILITY_PROBE_INTERVAL_SECONDS", 120, cast=int)

# PromQL label selectors identifying each check, e.g. job="jina-connect-api".
AVAILABILITY_PROBE_SELECTORS = {
    "api": config("AVAILABILITY_PROBE_SELECTOR_API", ""),
    "ui": config("AVAILABILITY_PROBE_SELECTOR_UI", ""),
}

# A check interval counts as failed when fewer than this fraction of probe
# locations succeeded. At the 0.5 default a majority must fail, so one flaky
# location cannot report the platform down — and a two-location check needs
# both to fail, which is the conservative reading.
AVAILABILITY_FAILURE_THRESHOLD = config("AVAILABILITY_FAILURE_THRESHOLD", 0.5, cast=float)

# A day counts towards coverage only once it holds at least this fraction of
# the checks it should. Without it a day holding five of 720 intervals would
# read as fully covered and its near-total absence of evidence would be
# averaged in as though it were a measurement.
AVAILABILITY_MIN_DAY_COVERAGE = config("AVAILABILITY_MIN_DAY_COVERAGE", 0.9, cast=float)

PARTNER_NAME = config("PARTNER_NAME", "Partner")
PARTNER_REPORT_RECIPIENTS = [
    address.strip()
    for address in config("PARTNER_REPORT_RECIPIENTS", "reports@example.invalid").split(",")
    if address.strip()
]

BASE_URL = config("BASE_URL", "http://localhost:8000")
FRONTEND_URL = config("FRONTEND_URL", "http://localhost:3000")
DEFAULT_WEBHOOK_BASE_URL = config("DEFAULT_WEBHOOK_BASE_URL", config("SITE_URL", "http://localhost:8000"))

# ── Telegram Bot API settings ──
TELEGRAM_MAX_RETRIES = config("TELEGRAM_MAX_RETRIES", 3, cast=int)
TELEGRAM_REQUEST_TIMEOUT = config("TELEGRAM_REQUEST_TIMEOUT", 30, cast=int)

RAZORPAY_KEY_ID = config("RAZORPAY_KEY_ID", "")
RAZORPAY_KEY_SECRET = config("RAZORPAY_KEY_SECRET", "")
RAZORPAY_WEBHOOK_SECRET = config("RAZORPAY_WEBHOOK_SECRET", "")
RAZORPAY_URL = config("RAZORPAY_URL", "https://api.razorpay.com/v1/")

# Email Configuration
EMAIL_BACKEND = config("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", 587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", "Jina Connect <noreply@jinaconnect.com>")

MEDIA_URL = "/media/"

# Local-storage upload directory. Ignored when STORAGE_BACKEND is s3 or gcs,
# which is what production uses.
#
# The default stays inside BASE_DIR so existing installs keep finding their
# files — moving it silently would make uploads disappear on upgrade. But it
# is a poor place for runtime state: a deploy-time `git clean -xfd` will take
# uploads with it. Any deployment relying on local storage should point this
# somewhere durable, e.g. MEDIA_ROOT=/var/lib/jina-connect/media.
MEDIA_ROOT = config("MEDIA_ROOT", os.path.join(BASE_DIR, "media"))

# Cloud Storage Configuration
# Set STORAGE_BACKEND to 's3', 'gcs', or 'local' (default)
STORAGE_BACKEND = config("STORAGE_BACKEND", "local")

if STORAGE_BACKEND == "s3":
    # AWS S3 Configuration
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", "")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", "")
    AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", "ap-south-1")
    AWS_S3_FILE_OVERWRITE = config("AWS_S3_FILE_OVERWRITE", False, cast=bool)
    AWS_DEFAULT_ACL = config("AWS_DEFAULT_ACL", None)
    AWS_S3_CUSTOM_DOMAIN = config("AWS_S3_CUSTOM_DOMAIN", None)
    AWS_QUERYSTRING_AUTH = config("AWS_QUERYSTRING_AUTH", True, cast=bool)

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    # Override MEDIA_URL so .url returns full S3 path
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
    else:
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/"

elif STORAGE_BACKEND == "gcs":
    # ─── Google Cloud Storage Configuration ───────────────────────────────
    # Required env vars:
    #   GS_BUCKET_NAME        – your GCS bucket (e.g. "jina-connect-media")
    #   GS_PROJECT_ID         – GCP project id
    # Optional:
    #   GS_CREDENTIALS        – absolute path to service account JSON file
    #                           (if not set, uses Application Default Credentials
    #                            i.e. GOOGLE_APPLICATION_CREDENTIALS env var or
    #                            the GCE/Cloud Run service account)
    #   GS_CUSTOM_DOMAIN      – custom CDN domain (e.g. "cdn.jinaconnect.com")
    #   GS_DEFAULT_ACL        – None = uniform bucket-level access (recommended)
    #   GS_QUERYSTRING_AUTH   – True = signed URLs (private bucket, default)
    #                           False = public URLs (public bucket)
    #   GS_EXPIRATION         – signed URL TTL in seconds (default 86400 = 24 hours)
    #                           V4 signed URLs support up to 604800 (7 days)
    #   GS_FILE_OVERWRITE     – False = always generate unique names (default)
    # ──────────────────────────────────────────────────────────────────────

    GS_BUCKET_NAME = config("GS_BUCKET_NAME", "")
    GS_PROJECT_ID = config("GS_PROJECT_ID", "")
    GS_DEFAULT_ACL = config("GS_DEFAULT_ACL", None)
    GS_QUERYSTRING_AUTH = config("GS_QUERYSTRING_AUTH", True, cast=bool)
    GS_FILE_OVERWRITE = config("GS_FILE_OVERWRITE", False, cast=bool)
    GS_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB — files larger than this spool to disk
    GS_BLOB_CHUNK_SIZE = 5 * 1024 * 1024  # 5 MB upload chunks (for resumable uploads)

    # Signed URL expiration (only used when GS_QUERYSTRING_AUTH=True)
    # Default: 7 days (V4 max).  The /serve/ endpoint generates fresh
    # signed URLs on every request so this is just a safety-net.
    from datetime import timedelta as _td

    GS_EXPIRATION = _td(seconds=config("GS_EXPIRATION", 604800, cast=int))

    # Credentials — load from service account JSON if path provided,
    # otherwise fall back to Application Default Credentials (ADC).
    _gs_creds_path = config("GS_CREDENTIALS", None)
    if _gs_creds_path:
        from google.oauth2 import service_account

        GS_CREDENTIALS = service_account.Credentials.from_service_account_file(_gs_creds_path)
    # else: GS_CREDENTIALS is not set → django-storages uses ADC automatically

    # Custom CDN domain (optional)
    GS_CUSTOM_ENDPOINT = config("GS_CUSTOM_DOMAIN", None)

    STORAGES = {
        "default": {
            "BACKEND": "jina_connect.storage_backends.ORBSafeGoogleCloudStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    # Override MEDIA_URL so FileField.url returns the correct domain
    _custom_domain = config("GS_CUSTOM_DOMAIN", None)
    if _custom_domain:
        MEDIA_URL = f"https://{_custom_domain}/"
    elif not GS_QUERYSTRING_AUTH:
        # Public bucket — direct GCS URL
        MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/"
    # else: signed URLs — .url is generated dynamically by django-storages

# else: local storage (default Django behavior — MEDIA_ROOT folder)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "users.User"
SITE_ID = 1

CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_ENABLE_UTC = False

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_RESULT_EXTENDED = True


CELERY_CACHE_BACKEND = "django-cache"

WHATSAPP_ENABLED = config("WHATSAPP_ENABLED", False, cast=bool)

WHATSAPP_API_TOKEN = config("WHATSAPP_API_TOKEN", "")

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",  # Redis running on localhost
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }


SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Basic": {"type": "basic"},
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
        },
    },
    "USE_SESSION_AUTH": True,
    "DEFAULT_API_URL": config("DEFAULT_API_URL", "http://localhost:8000", cast=str),
}


# Django Crontab Configuration
CRONJOBS = [
    # Check WhatsApp template statuses every 2 minutes
    (
        "*/2 * * * *",
        "wa.cron.check_template_status",
        ">> " + os.path.join(BASE_DIR, "jina_cron_template_status.log 2>&1"),
    ),
    # Check broadcast message completion and update broadcast status every minute
    (
        "* * * * *",
        "broadcast.cron.update_broadcast_status",
        ">> " + os.path.join(BASE_DIR, "jina_cron_broadcast_status.log 2>&1"),
    ),
    # Clean up notifications older than 90 days — runs daily at 3 AM
    (
        "0 3 * * *",
        "notifications.cron.cleanup_old_notifications",
        ">> " + os.path.join(BASE_DIR, "jina_cron_notification_cleanup.log 2>&1"),
    ),
    # Reset per-app SMS daily counters at midnight
    (
        "0 0 * * *",
        "sms.cron.reset_daily_sms_counters",
        ">> " + os.path.join(BASE_DIR, "jina_cron_sms_daily_reset.log 2>&1"),
    ),
    # Reset per-app RCS daily counters at midnight
    (
        "0 0 * * *",
        "rcs.cron.reset_daily_rcs_counters",
        ">> " + os.path.join(BASE_DIR, "jina_cron_rcs_daily_reset.log 2>&1"),
    ),
    # Copy yesterday's synthetic-monitoring results into DailyAvailability —
    # 01:30 daily, late enough that the day is closed in local time and early
    # enough that the 1st-of-month report at 06:30 has the final day's row.
    (
        "30 1 * * *",
        "availability.cron.aggregate_daily_availability",
        ">> " + os.path.join(BASE_DIR, "jina_cron_availability_aggregate.log 2>&1"),
    ),
    # Active Customer Account report (partner agreement Cl. 4.2) — 06:00 on
    # the 1st, covering the month that just ended. Scheduled here rather than
    # with celery beat because this deployment has no beat process: every
    # periodic job runs through django-crontab, and a Celery task alone would
    # never fire (#230). Delivery is recorded, so a duplicate schedule cannot
    # send a partner the same statement twice.
    (
        "0 6 1 * *",
        "tenants.cron.send_monthly_active_account_report",
        ">> " + os.path.join(BASE_DIR, "jina_cron_partner_report.log 2>&1"),
    ),
    # Service availability report (partner agreement Cl. 5.4) — 06:30 on the
    # 1st, half an hour after the account report so the two do not contend.
    # Refuses to send when the month has no monitoring data rather than
    # emailing a figure computed from nothing.
    (
        "30 6 1 * *",
        "availability.cron.send_monthly_availability_report",
        ">> " + os.path.join(BASE_DIR, "jina_cron_availability_report.log 2>&1"),
    ),
    # Example: Uncomment below to sync gupshup auth templates every 15 minutes
    # ("*/15 * * * *", "gupshup.cron.sync_gupshup_auth_templates", ">> " + os.path.join(BASE_DIR, "gupshup_sync.log 2>&1")),
]


# Use Redis as broker
CELERY_BROKER_URL = config("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = True
CELERY_TASK_TRACK_STARTED = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Celery beat — periodic tasks
CELERY_BEAT_SCHEDULE = {
    "partner-active-account-report": {
        # Cl. 4.2: email the previous month's Active Customer Account report on
        # the 1st at 06:00 local. Runs after the month has ended, never during.
        "task": "tenants.tasks.send_monthly_active_account_report",
        "schedule": __import__("celery.schedules", fromlist=["crontab"]).crontab(day_of_month=1, hour=6, minute=0),
    },
    "voice-enforce-recording-retention": {
        # Hard-delete expired recordings nightly at 02:30 in the
        # configured CELERY_TIMEZONE (Asia/Kolkata).
        "task": "voice.recordings.tasks.enforce_retention",
        "schedule": __import__("celery.schedules", fromlist=["crontab"]).crontab(hour=2, minute=30),
    },
}


# ── Voice channel ──────────────────────────────────────────────────────
# Recordings live in their own S3 bucket so retention rules / lifecycle
# policies can be applied independently of the main media bucket.
VOICE_RECORDING_STORAGE_BUCKET = config("VOICE_RECORDING_STORAGE_BUCKET", "")
VOICE_MAX_CALL_DURATION_SECONDS = config("VOICE_MAX_CALL_DURATION_SECONDS", 3600, cast=int)

# Transcription backend selection (#169). Set to "" to disable
# transcription entirely; "deepgram" / "whisper" / "provider_native"
# pick the corresponding backend in ``voice.transcription``.
VOICE_TRANSCRIPTION_PROVIDER = config("VOICE_TRANSCRIPTION_PROVIDER", "")
DEEPGRAM_API_KEY = config("DEEPGRAM_API_KEY", "")
OPENAI_API_KEY = config("OPENAI_API_KEY", "")

# Asterisk (only needed for SIP voice — HTTP voice providers don't touch this).
ASTERISK_ARI_URL = config("ASTERISK_ARI_URL", "")
ASTERISK_ARI_USER = config("ASTERISK_ARI_USER", "")
ASTERISK_ARI_PASSWORD = config("ASTERISK_ARI_PASSWORD", "")
ASTERISK_ARI_APP_NAME = config("ASTERISK_ARI_APP_NAME", "jina-voice")
# Directory where rendered PJSIP fragments are dropped for Asterisk
# to ``pjsip reload``. Empty → falls back to ``<project>/asterisk-config/pjsip.d``.
ASTERISK_PJSIP_DROP_DIR = config("ASTERISK_PJSIP_DROP_DIR", "")


GUPSHUP_BASE_URL = config("GUPSHUP_BASE_URL", "")

# Broadcast Configuration
# Time limit (in minutes) within which a broadcast can be cancelled after scheduling
BROADCAST_CANCELLATION_TIME_LIMIT_IN_MINUTES = config("BROADCAST_CANCELLATION_TIME_LIMIT_IN_MINUTES", 0.05, cast=float)

# Transaction ID Configuration
TRANSACTION_ID_PREFIX = config("TRANSACTION_ID_PREFIX", "jc")  # Prefix for system-generated transaction IDs

# Batch processing settings for broadcasts
BROADCAST_BATCH_SIZE = config("BROADCAST_BATCH_SIZE", 50, cast=int)  # Number of contacts per batch
BROADCAST_BATCH_DELAY = config("BROADCAST_BATCH_DELAY", 5, cast=int)  # Seconds between batches
BROADCAST_MAX_RETRIES = config("BROADCAST_MAX_RETRIES", 3, cast=int)  # Maximum retry attempts for failed messages
BROADCAST_CLEANUP_DAYS = config("BROADCAST_CLEANUP_DAYS", 30, cast=int)  # Days to keep completed broadcast data

# Platform-specific rate limits (messages per minute)
PLATFORM_RATE_LIMITS = {
    "whatsapp": config("WHATSAPP_RATE_LIMIT", 100, cast=int),
    "telegram": config("TELEGRAM_RATE_LIMIT", 30, cast=int),
    "sms": config("SMS_RATE_LIMIT", 100, cast=int),
    "rcs": config("RCS_RATE_LIMIT", 300, cast=int),
    "email": config("EMAIL_RATE_LIMIT", 300, cast=int),
}

# Channels Configuration for WebSocket support
ASGI_APPLICATION = "jina_connect.routing.application"

# Channel layers configuration using Redis
REDIS_URL = config("REDIS_URL", "redis://localhost:6379/0")

# chat_flow node-type registry: log a warning when a flow contains an unknown
# node ``type`` instead of rejecting it. Useful while existing channels have
# not yet migrated their node types to the registry. Set False in prod once
# the registry is fully populated.
WARN_ON_UNKNOWN_NODE_TYPES = config("WARN_ON_UNKNOWN_NODE_TYPES", default=True, cast=bool)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            "capacity": 1500,  # Maximum number of messages to store
            "expiry": 60,  # Message expiry in seconds
        },
    },
}


# WebSocket Configuration
WEBSOCKET_ACCEPT_ALL = config("WEBSOCKET_ACCEPT_ALL", True, cast=bool)
WEBSOCKET_TOKEN_EXPIRY = config("WEBSOCKET_TOKEN_EXPIRY", 3600, cast=int)  # 1 hour

# Team Inbox Configuration
TEAM_INBOX_MESSAGE_LIMIT = config("TEAM_INBOX_MESSAGE_LIMIT", 100, cast=int)
TEAM_INBOX_TYPING_TIMEOUT = config("TEAM_INBOX_TYPING_TIMEOUT", 5, cast=int)  # seconds

SERIALIZATION_MODULES = {"json": "djmoney.serializers"}
OPEN_EXCHANGE_RATES_APP_ID = config("OPEN_EXCHANGE_RATES_APP_ID", "")
EXCHANGE_BACKEND = "djmoney.contrib.exchange.backends.OpenExchangeRatesBackend"

GUPSHUP_EMAIL = config("GUPSHUP_EMAIL", "")
GUPSHUP_PASSWORD = config("GUPSHUP_PASSWORD", "")


# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================

# Log directory - configurable via environment variable
# Default: /var/log/jina-connect (production) or ./logs (local)
LOG_DIR = config("LOG_DIR", default=str(BASE_DIR / "logs"))
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "chatflow_file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "chatflow.log"),
            "formatter": "simple",
        },
    },
    "loggers": {
        "drf_yasg": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        # ChatFlow app logging
        "chat_flow": {
            "handlers": ["console", "chatflow_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "chat_flow.services.graph_executor": {
            "handlers": ["console", "chatflow_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # WhatsApp app logging
        "wa": {
            "handlers": ["console", "chatflow_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "wa.tasks": {
            "handlers": ["console", "chatflow_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # Broadcast app logging
        "broadcast": {
            "handlers": ["console", "chatflow_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "broadcast.tasks": {
            "handlers": ["console", "chatflow_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# =============================================================================
# DEEP LINKING CONFIGURATION
# For iOS Universal Links and Android App Links
# =============================================================================

# Site URL - The backend domain used for generating deep links in emails
# Emails always link to backend; backend decides where to redirect
SITE_URL = config("SITE_URL", "http://localhost:8000")

# Note: FRONTEND_URL (defined earlier in settings) is used for web redirects
# FRONTEND_URL = http://localhost:3000

# iOS Configuration
APPLE_TEAM_ID = config("APPLE_TEAM_ID", "XXXXXXXXXX")  # Your Apple Developer Team ID
IOS_BUNDLE_ID = config("IOS_BUNDLE_ID", "com.jinacode.jinaconnect")  # Your iOS app bundle identifier
IOS_APP_STORE_URL = config("IOS_APP_STORE_URL", "https://apps.apple.com/app/jina-connect/id123456789")

# Android Configuration
ANDROID_PACKAGE_NAME = config("ANDROID_PACKAGE_NAME", "com.jinacode.jinaconnect")  # Your Android package name
ANDROID_PLAY_STORE_URL = config(
    "ANDROID_PLAY_STORE_URL", "https://play.google.com/store/apps/details?id=com.jinacode.jinaconnect"
)

# Android SHA-256 Certificate Fingerprints
# Get these using: keytool -list -v -keystore your-keystore.jks
# Format: "XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX"
# You can have multiple fingerprints (debug + release) - comma separated
ANDROID_SHA256_FINGERPRINTS = config(
    "ANDROID_SHA256_FINGERPRINTS", default="", cast=lambda v: [x.strip() for x in v.split(",")] if v else []
)

# Custom URL Scheme for fallback (when Universal/App Links fail)
MOBILE_APP_SCHEME = config("MOBILE_APP_SCHEME", "jinaconnect")

META_PERM_TOKEN = config("META_PERM_TOKEN", "")
META_APP_SECRET = config("META_APP_SECRET", "")  # Used for X-Hub-Signature-256 verification
META_WEBHOOK_VERIFY_TOKEN = config("META_WEBHOOK_VERIFY_TOKEN", "")  # Used for hub.verify_token challenge
