# Generated by Django 5.1.6 on 2026-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broadcast", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="media_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Override template media at send time. Format: {"header": <TenantMedia id>} for single-media templates, {"cards": {"0": <TenantMedia id>, "1": <TenantMedia id>, ...}} for carousels.',
            ),
        ),
        migrations.AddField(
            model_name="historicalbroadcast",
            name="media_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Override template media at send time. Format: {"header": <TenantMedia id>} for single-media templates, {"cards": {"0": <TenantMedia id>, "1": <TenantMedia id>, ...}} for carousels.',
            ),
        ),
    ]
