# Generated by Django 5.1.6 on 2026-02-25 15:10

import broadcast.url_tracker.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_add_media_overrides'),
        ('contacts', '0003_tenantcontact_dnc_tenantcontact_last_called_at_and_more'),
        ('tenants', '0012_media_id_charfield_to_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=broadcast.url_tracker.models._generate_short_code, editable=False, max_length=16, unique=True)),
                ('original_url', models.URLField(max_length=2048)),
                ('button_index', models.PositiveSmallIntegerField(default=0, help_text='Index of the URL button in the template')),
                ('button_text', models.CharField(blank=True, default='', help_text="Display text of the button (e.g. 'Shop Now')", max_length=100)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('first_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(blank=True, help_text='Broadcast this link belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_urls', to='broadcast.broadcast')),
                ('broadcast_message', models.ForeignKey(blank=True, help_text='Per-recipient broadcast message this link belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_urls', to='broadcast.broadcastmessage')),
                ('contact', models.ForeignKey(blank=True, help_text='Contact who received this tracked link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_urls', to='contacts.tenantcontact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_urls', to='tenants.tenant')),
            ],
            options={
                'db_table': 'broadcast_tracked_url',
            },
        ),
        migrations.CreateModel(
            name='TrackedURLClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('referer', models.URLField(blank=True, default='', max_length=2048)),
                ('tracked_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='broadcast.trackedurl')),
            ],
            options={
                'db_table': 'broadcast_tracked_url_click',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackedurl',
            index=models.Index(fields=['tenant', 'broadcast'], name='broadcast_t_tenant__46af57_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedurl',
            index=models.Index(fields=['contact'], name='broadcast_t_contact_0d1b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedurl',
            index=models.Index(fields=['broadcast_message'], name='broadcast_t_broadca_b97e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedurl',
            index=models.Index(fields=['created_at'], name='broadcast_t_created_455c25_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedurlclick',
            index=models.Index(fields=['tracked_url', 'clicked_at'], name='broadcast_t_tracked_1ef57b_idx'),
        ),
    ]
