# Generated by Django 5.1.15 on 2026-05-15 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broadcast", "0008_broadcast_fallback_sms_enabled"),
        ("voice", "0004_rename_voice_recor_tenant__idx_voice_recor_tenant__a286dc_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalbroadcast",
            name="voice_template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Voice template for VOICE-platform broadcasts (TTS / pre-recorded audio).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="voice.voicetemplate",
            ),
        ),
    ]
