# Generated by Django 5.2.16 on 2026-09-10 14:39

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("broadcast", "0009_alter_historicalbroadcast_voice_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="initial_cost_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="refund_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbroadcast",
            name="initial_cost_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbroadcast",
            name="refund_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
