# Generated by Django 5.1.6 on 2026-02-17 07:07

"""
Data migration: seed default RBAC roles for every existing tenant and assign
all existing TenantUser records to the OWNER role.

This is idempotent — safe to run multiple times.
"""

from django.db import migrations


# ---------------------------------------------------------------------------
# Inline copy of constants from tenants/permissions.py so the migration is
# self-contained and not affected by future code changes.
# ---------------------------------------------------------------------------

ALL_PERMISSIONS = [
    "tenant.view", "tenant.edit", "tenant.delete", "tenant.transfer",
    "users.view", "users.invite", "users.change_role", "users.remove",
    "billing.view", "billing.manage",
    "wa_app.view", "wa_app.manage", "rate_card.manage",
    "template.view", "template.create", "template.edit",
    "template.delete", "template.submit",
    "broadcast.view", "broadcast.create", "broadcast.cancel",
    "broadcast.charge_breakdown",
    "contact.view", "contact.create", "contact.edit", "contact.delete",
    "contact.import", "contact.export",
    "inbox.view", "inbox.reply", "inbox.assign", "inbox.resolve",
    "chatflow.view", "chatflow.create", "chatflow.edit",
    "chatflow.delete", "chatflow.toggle",
    "product.view", "product.manage",
    "analytics.view",
]

DEFAULT_ROLE_PERMISSIONS = {
    "owner": {p: True for p in ALL_PERMISSIONS},
    "admin": {
        **{p: True for p in ALL_PERMISSIONS},
        "tenant.delete": False,
        "tenant.transfer": False,
    },
    "manager": {
        "tenant.view": True, "users.view": True, "billing.view": True,
        "wa_app.view": True,
        "template.view": True, "template.create": True, "template.edit": True,
        "template.delete": True, "template.submit": True,
        "broadcast.view": True, "broadcast.create": True,
        "broadcast.cancel": True, "broadcast.charge_breakdown": True,
        "contact.view": True, "contact.create": True,
        "contact.edit": True, "contact.delete": True,
        "contact.import": True, "contact.export": True,
        "inbox.view": True, "inbox.reply": True,
        "inbox.assign": True, "inbox.resolve": True,
        "chatflow.view": True, "chatflow.create": True,
        "chatflow.edit": True, "chatflow.delete": True,
        "chatflow.toggle": True,
        "product.view": True, "product.manage": True,
        "analytics.view": True,
    },
    "agent": {
        "tenant.view": True, "users.view": True,
        "wa_app.view": True, "template.view": True,
        "broadcast.view": True, "contact.view": True,
        "inbox.view": True, "inbox.reply": True,
        "chatflow.view": True, "product.view": True,
        "analytics.view": True,
    },
    "viewer": {
        "tenant.view": True, "users.view": True, "billing.view": True,
        "wa_app.view": True, "template.view": True,
        "broadcast.view": True, "contact.view": True,
        "inbox.view": True, "chatflow.view": True,
        "product.view": True, "analytics.view": True,
    },
}

ROLE_DEFS = [
    {"slug": "owner",   "name": "Owner",   "priority": 100, "is_editable": False},
    {"slug": "admin",   "name": "Admin",   "priority": 80,  "is_editable": True},
    {"slug": "manager", "name": "Manager", "priority": 60,  "is_editable": True},
    {"slug": "agent",   "name": "Agent",   "priority": 40,  "is_editable": True},
    {"slug": "viewer",  "name": "Viewer",  "priority": 20,  "is_editable": True},
]


def seed_roles_and_assign_owner(apps, schema_editor):
    """
    Forward migration:
    1. Create 5 default TenantRole records per existing tenant.
    2. Create RolePermission rows for each role.
    3. Set every existing TenantUser.role → tenant's OWNER role.
    """
    Tenant = apps.get_model("tenants", "Tenant")
    TenantRole = apps.get_model("tenants", "TenantRole")
    RolePermission = apps.get_model("tenants", "RolePermission")
    TenantUser = apps.get_model("tenants", "TenantUser")

    for tenant in Tenant.objects.all():
        owner_role = None

        for role_def in ROLE_DEFS:
            role, _ = TenantRole.objects.get_or_create(
                tenant=tenant,
                slug=role_def["slug"],
                defaults={
                    "name": role_def["name"],
                    "priority": role_def["priority"],
                    "is_system": True,
                    "is_editable": role_def["is_editable"],
                },
            )

            if role_def["slug"] == "owner":
                owner_role = role

            # Seed permission rows
            default_perms = DEFAULT_ROLE_PERMISSIONS.get(role_def["slug"], {})
            for perm_key in ALL_PERMISSIONS:
                RolePermission.objects.get_or_create(
                    role=role,
                    permission=perm_key,
                    defaults={"allowed": default_perms.get(perm_key, False)},
                )

        # Assign all existing TenantUsers in this tenant to OWNER
        if owner_role:
            TenantUser.objects.filter(tenant=tenant, role__isnull=True).update(
                role=owner_role
            )


def reverse_seed(apps, schema_editor):
    """
    Reverse migration: remove all system roles and clear TenantUser.role FK.
    """
    TenantRole = apps.get_model("tenants", "TenantRole")
    TenantUser = apps.get_model("tenants", "TenantUser")

    # Clear role FK on all TenantUsers first
    TenantUser.objects.all().update(role=None)

    # Delete all system roles (cascades to RolePermission rows)
    TenantRole.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_rbac_add_tenantrole_rolepermission'),
    ]

    operations = [
        migrations.RunPython(seed_roles_and_assign_owner, reverse_seed),
    ]
