# Generated by Django 5.1.6 on 2026-02-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0010_add_commerce_manager_to_wa_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantmedia",
            name="media_id",
            field=models.TextField(
                blank=True, help_text="Media ID returned by WhatsApp (Gupshup) after media upload.", null=True
            ),
        ),
    ]
