# Generated by Django 5.1.6 on 2026-02-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_media_id_charfield_to_textfield'),
    ]

    operations = [
    ]
