# Generated by Django 5.1.6 on 2026-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_add_payment_config_to_tenant_wa_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmedia',
            name='platform',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('VOICE', 'Voice')], default='WHATSAPP', max_length=50),
        ),
    ]
