# Generated by Django 5.2.16 on 2026-09-10 14:39

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0022_historicaltenant_archived_at_tenant_archived_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltenant",
            name="balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltenant",
            name="credit_line_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltenant",
            name="threshold_alert_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="credit_line_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="threshold_alert_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tenantwaapp",
            name="authentication_message_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tenantwaapp",
            name="marketing_message_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tenantwaapp",
            name="utility_message_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
    ]
