# Generated by Django 5.2.16 on 2026-09-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0023_alter_historicaltenant_balance_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentPartnerReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("active_accounts", "Active Customer Account report"),
                            ("availability", "Service availability report"),
                        ],
                        max_length=32,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("recipients", models.TextField(help_text="Who it went to, as sent.")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sent partner report",
                "verbose_name_plural": "Sent partner reports",
                "ordering": ["-year", "-month"],
                "constraints": [
                    models.UniqueConstraint(fields=("kind", "year", "month"), name="unique_partner_report_per_period")
                ],
            },
        ),
    ]
