# Generated by Django 5.1.6 on 2026-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="metabusinessconnection",
            new_name="meta_metabu_tenant__eee1da_idx",
            old_name="meta_conn_t_reauth_idx",
        ),
        migrations.AddField(
            model_name="metabusinessconnection",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metabusinessconnection",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
