# Generated by Django 5.1.6 on 2026-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_flow', '0004_backfill_session_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatflowsession',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text="Reason session was ended prematurely (e.g., 'Flow deactivated for editing')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatflow',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this flow is active and can accept new sessions'),
        ),
    ]
