# Generated by Django 5.1.6 on 2026-04-11 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_flow', '0005_userchatflowsession_cancellation_reason_and_more'),
        ('wa', '0012_increase_media_url_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatflow',
            name='flow_data',
            field=models.JSONField(help_text='\n        Complete ReactFlow JSON structure containing the visual flow design.\n\n        Expected Structure:\n        {\n            "nodes": [\n                {\n                    "id": "welcome-node",\n                    "type": "template",\n                    "position": {"x": 100, "y": 100},\n                    "data": {\n                        "template_id": 123,\n                        "label": "Welcome Message",\n                        "buttons": [...]\n                    }\n                }\n            ],\n            "edges": [\n                {\n                    "id": "edge-1",\n                    "source": "welcome-node",\n                    "target": "menu-node",\n                    "data": {\n                        "button_id": "btn-get-started",\n                        "button_text": "Get Started"\n                    }\n                }\n            ],\n            "viewport": {"x": 0, "y": 0, "zoom": 1}\n        }\n\n        This JSON is generated by the ReactFlow visual editor and contains all the information\n        needed to recreate the flow design, including node positions, connections, and styling.\n        '),
        ),
        migrations.AlterField(
            model_name='chatflow',
            name='start_template',
            field=models.ForeignKey(blank=True, help_text='\n        The WhatsApp template that users will see first when they start this flow.\n\n        Requirements:\n        - Must be an APPROVED template (not pending or rejected)\n        - Must have at least one button (flows require user interaction)\n        - Must belong to the same tenant as this flow\n        - Can be null for draft/inactive flows that are still being designed\n\n        Example:\n        If start_template is "Welcome Message" with buttons ["Get Started", "More Info"],\n        then users will see this message first and can click either button to proceed.\n\n        The start_template determines the first node that users land on when beginning\n        a new chat flow session.\n        ', limit_choices_to={'buttons__isnull': False, 'status': 'APPROVED'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows_as_start', to='wa.watemplate'),
        ),
        migrations.AlterField(
            model_name='chatflowedge',
            name='button_text',
            field=models.CharField(help_text='\n        The exact text of the button that triggers this edge transition.\n\n        IMPORTANT: This must match the button text in the source node\'s template exactly.\n\n        Examples: "Order Pizza", "Contact Support", "Yes, Continue"\n\n        Button Matching Process:\n        1. User clicks button in WhatsApp\n        2. System receives button text from WhatsApp API\n        3. System finds edge where button_text matches the clicked text\n        4. System transitions user to target_node\n\n        Legacy vs Modern Approach:\n        - Legacy: Uses button_text for matching (this field)\n        - Modern: Uses button_id from edge_data (more reliable)\n\n        Both approaches are supported for backward compatibility.\n        ', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatflowedge',
            name='button_type',
            field=models.CharField(help_text='\n        The type of button that triggers this transition.\n\n        WhatsApp Button Types:\n        - "QUICK_REPLY": Simple text button (most common)\n        - "URL": Button that opens a website\n        - "PHONE_NUMBER": Button that initiates a phone call\n        - "OTP": Button for OTP/authentication flows\n\n        This field helps with:\n        - Validation during flow creation\n        - Analytics and reporting\n        - Future button-type-specific behaviors\n\n        Must match the button type defined in the source template.\n        ', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatflowedge',
            name='edge_data',
            field=models.JSONField(default=dict, help_text='\n        Additional configuration and metadata for this edge transition.\n\n        Modern Structure (Recommended):\n        {\n            "button_id": "btn-order-pizza",        // Unique button identifier\n            "button_text": "Order Pizza",          // Fallback text matching\n            "button_type": "QUICK_REPLY",          // Button type\n            "analytics_label": "main_cta",         // Custom analytics tag\n            "conditions": {                        // Future: conditional logic\n                "user_type": "premium"\n            },\n            "delay_seconds": 2                     // Future: delayed responses\n        }\n\n        Key Features:\n        1. button_id: Modern, reliable button identification\n        2. Analytics: Custom labels for tracking specific user paths\n        3. Conditions: Future support for conditional edges\n        4. Timing: Future support for delayed message delivery\n\n        Migration Path:\n        - Legacy edges use only button_text matching\n        - Modern edges prefer button_id with button_text fallback\n        - Both approaches work simultaneously for compatibility\n\n        Benefits of button_id:\n        - Survives template text changes\n        - Supports multiple languages\n        - Prevents typo-related bugs\n        - Enables better debugging\n        '),
        ),
        migrations.AlterField(
            model_name='chatflowedge',
            name='edge_id',
            field=models.CharField(help_text='\n        Unique identifier for this edge within the ReactFlow visual editor.\n\n        Examples: "welcome-to-menu", "payment-to-confirmation", "edge-1"\n\n        Used for:\n        - Visual editor state management\n        - Debugging conversation flows\n        - Maintaining edge references in ReactFlow JSON\n\n        Must be unique within the flow.\n        ', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatflowedge',
            name='source_node',
            field=models.ForeignKey(help_text='\n        The node that users are leaving when they click the button.\n\n        This is the "current" node where the user sees a message and buttons.\n        When they click a button, this edge defines where they go next.\n\n        Example: User is viewing "Pizza Menu" node and clicks "Add to Cart"\n        → source_node = "Pizza Menu" node\n        ', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='chat_flow.chatflownode'),
        ),
        migrations.AlterField(
            model_name='chatflowedge',
            name='target_node',
            field=models.ForeignKey(help_text='\n        The node that users will see after clicking the button.\n\n        This is the "destination" node that becomes the user\'s new current position.\n\n        Example: User clicks "Add to Cart" button\n        → target_node = "Shopping Cart" node\n\n        The user\'s session will be updated to show them at the target_node,\n        and they\'ll receive the target node\'s template message.\n        ', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='chat_flow.chatflownode'),
        ),
        migrations.AlterField(
            model_name='chatflownode',
            name='node_data',
            field=models.JSONField(default=dict, help_text='\n        Additional configuration data specific to this node within the flow context.\n\n        Common Use Cases:\n        1. Button overrides - Customize button layout for this specific flow\n        2. Display labels - Human-readable names for the visual editor\n        3. Conditional logic - Parameters for future conditional nodes\n        4. Analytics tags - Custom tracking labels for this node\n\n        Example Structure:\n        {\n            "label": "Pizza Selection",\n            "buttons": [\n                {\n                    "id": "btn-margherita",\n                    "text": "Margherita",\n                    "type": "QUICK_REPLY",\n                    "template_button_index": 0\n                }\n            ],\n            "analytics_tags": ["menu", "pizza"],\n            "display_priority": 1\n        }\n\n        Key Benefits:\n        - Allows same template to behave differently in different flows\n        - Enables flow-specific customizations without modifying templates\n        - Supports visual editor metadata that doesn\'t belong in templates\n        - Future-proofs for advanced node features\n        '),
        ),
        migrations.AlterField(
            model_name='chatflownode',
            name='node_id',
            field=models.CharField(help_text='\n        Unique identifier for this node within the ReactFlow visual editor.\n\n        Examples: "welcome-node", "pizza-menu", "payment-options"\n\n        This ID is used to:\n        - Reference nodes in the ReactFlow JSON structure\n        - Connect nodes with edges in the visual editor\n        - Debug and trace user paths through flows\n\n        Must be unique within the flow.\n        ', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatflownode',
            name='node_type',
            field=models.CharField(default='template', help_text='\n        Type of node determining its behavior in the flow.\n\n        Available Types:\n        - "template": Standard message node that displays a WhatsApp template\n        - "condition": Logic node for conditional branching (future feature)\n        - "action": Integration node for external API calls (future feature)\n\n        Currently, most nodes are "template" type since they represent WhatsApp messages.\n        ', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatflownode',
            name='position_x',
            field=models.FloatField(help_text="\n        X coordinate of this node in the ReactFlow visual editor.\n\n        Used for:\n        - Saving and restoring visual flow layouts\n        - Organizing flows in a readable manner\n        - Maintaining designer's intended flow structure\n\n        Coordinate system starts at (0,0) in the top-left corner.\n        "),
        ),
        migrations.AlterField(
            model_name='chatflownode',
            name='position_y',
            field=models.FloatField(help_text='\n        Y coordinate of this node in the ReactFlow visual editor.\n\n        Used for:\n        - Saving and restoring visual flow layouts\n        - Creating logical top-to-bottom flow progression\n        - Grouping related nodes visually\n\n        Coordinate system starts at (0,0) in the top-left corner.\n        '),
        ),
        migrations.AlterField(
            model_name='chatflownode',
            name='template',
            field=models.ForeignKey(blank=True, help_text='\n        The approved WhatsApp template that will be sent when users reach this node.\n\n        Requirements:\n        - Must be APPROVED status (Gupshup has validated the template)\n        - Should belong to the same tenant as the flow\n        - Template content cannot be modified once approved\n\n        The template contains:\n        - Message text (e.g., "Welcome to our store!")\n        - Button definitions (text, types, actions)\n        - Media attachments (images, documents, etc.)\n        - Template metadata (category, language, etc.)\n\n        Example Template:\n        Content: "Your order status: {{1}}. What would you like to do?"\n        Buttons: ["Track Order", "Cancel Order", "Contact Support"]\n        ', limit_choices_to={'status': 'APPROVED'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='wa.watemplate'),
        ),
        migrations.AlterField(
            model_name='userchatflowsession',
            name='current_node_id',
            field=models.CharField(help_text="\n        The node_id of the node the contact is currently at.\n\n        This is the string node_id (e.g., 'welcome-node'), not the database ID.\n        After each step, this is updated to reflect where the user is.\n        ", max_length=255),
        ),
    ]
