# Generated by hand for foundation PR (#157).
#
# Adds ChatFlow.platform field to scope a flow to a specific channel. Existing
# flows back-fill to WHATSAPP via the default, matching current behaviour
# (the model was implicitly WhatsApp-only).

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_flow", "0006_alter_chatflow_flow_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatflow",
            name="platform",
            field=models.CharField(
                choices=[
                    ("WHATSAPP", "WhatsApp"),
                    ("TELEGRAM", "Telegram"),
                    ("SMS", "SMS"),
                    ("RCS", "RCS"),
                    ("EMAIL", "Email"),
                    ("VOICE", "Voice"),
                ],
                default="WHATSAPP",
                help_text="Platform this flow targets. Determines which node types are valid.",
                max_length=20,
            ),
        ),
    ]
