# Generated by Django 5.1.6 on 2026-05-19 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_campaign_insights"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adcreative",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="audiencetemplate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audiencetemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campaigninsights",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaigninsights",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaigninsights",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campaigninsights",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="adcreative",
            name="media_type",
            field=models.CharField(choices=[("image", "Image"), ("video", "Video")], max_length=10),
        ),
        migrations.AlterField(
            model_name="adcreative",
            name="media_url",
            field=models.TextField(help_text="URL of the uploaded asset (S3 / CDN)."),
        ),
        migrations.AlterField(
            model_name="campaigninsights",
            name="ctr_bp",
            field=models.IntegerField(default=0, help_text="Click-through rate, basis points (10000 = 100%)"),
        ),
    ]
