# Generated by Django 5.2.16 on 2026-09-10 14:39

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0003_alter_tenanttransaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenanttransaction",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("USD", "US Dollar"),
                    ("AED", "United Arab Emirates Dirham"),
                ],
                default="INR",
                editable=False,
                max_length=3,
            ),
        ),
    ]
