# Generated by Django 5.2.16 on 2026-09-10 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broadcast", "0010_alter_broadcast_initial_cost_currency_and_more"),
        ("razorpay", "0003_alter_razorpayorder_amount_currency"),
        ("tenants", "0023_alter_historicaltenant_balance_currency_and_more"),
        ("transaction", "0004_alter_tenanttransaction_amount_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenanttransaction",
            name="note",
            field=models.TextField(blank=True, default="", help_text="What happened, in the operator's words."),
        ),
        migrations.AddField(
            model_name="tenanttransaction",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The operator who applied this. Null for machine-generated rows.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applied_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenanttransaction",
            name="reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Invoice number or bank reference the credit was applied against.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="tenanttransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("PENDING RECHARGE", "PENDING RECHARGE"),
                    ("SUCCESS RECHARGE", "SUCCESS RECHARGE"),
                    ("FAILED RECHARGE", "FAILED RECHARGE"),
                    ("CONSUMPTION", "CONSUMPTION"),
                    ("REFUND", "REFUND"),
                    ("MANUAL CREDIT", "Manual credit (offline settlement)"),
                    ("MANUAL DEBIT", "Manual debit (correction)"),
                    ("VOICE_OUTBOUND", "Voice Outbound Call"),
                    ("VOICE_INBOUND", "Voice Inbound Call"),
                    ("VOICE_NUMBER_RENT", "Voice Number Rental"),
                    ("VOICE_AI_AGENT", "Voice AI Agent"),
                    ("VOICE_RECORDING", "Voice Recording"),
                ],
                default="CONSUMPTION",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="tenanttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction_type__in", ["MANUAL CREDIT", "MANUAL DEBIT"])),
                fields=("tenant", "reference"),
                name="unique_manual_reference_per_tenant",
            ),
        ),
    ]
