# Generated by Django 5.2.16 on 2026-10-02 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("github_repo", models.CharField(help_text="owner/repo the issue lives in.", max_length=200)),
                ("github_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("page_url", models.URLField(blank=True, max_length=2000)),
                ("reporter_name", models.CharField(blank=True, max_length=200)),
                ("reporter_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved — awaiting confirmation"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "close_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("confirmed", "Confirmed fixed by the customer"),
                            ("auto", "Closed automatically after no reply"),
                            ("support", "Closed by support"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assignee_login", models.CharField(blank=True, max_length=100)),
                ("reported_at", models.DateTimeField(help_text="When the issue was opened on GitHub.")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-reported_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("github_repo", "github_number"), name="support_ticket_unique_issue")
                ],
            },
        ),
        migrations.CreateModel(
            name="SupportTicketEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("received", "Report received"),
                            ("assigned", "Assigned to support"),
                            ("reply", "Reply from support"),
                            ("fix_ready", "Fix on its way"),
                            ("resolved", "Marked resolved"),
                            ("reopened", "Reopened"),
                            ("customer_comment", "Comment from the customer"),
                            ("closed", "Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        choices=[("support", "Support"), ("customer", "Customer"), ("system", "System")], max_length=10
                    ),
                ),
                ("agent_name", models.CharField(blank=True, max_length=100)),
                ("body", models.TextField(blank=True)),
                ("github_comment_id", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="support.supportticket"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
