# Generated by Django 5.1.6 on 2026-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attribution", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributionevent",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attributionevent",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="attributionevent",
            name="capi_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed (retryable)"),
                    ("skipped", "Skipped (consent / disabled)"),
                    ("dead_lettered", "Dead-lettered after retries"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attributionevent",
            name="event_name",
            field=models.CharField(help_text="Meta standard event name (Lead, Purchase, Custom).", max_length=40),
        ),
    ]
