# Generated by Django 5.1.6 on 2026-05-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attribution", "0002_attributionevent_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributionevent",
            name="capi_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_flight", "In flight (claimed by a flusher worker)"),
                    ("sent", "Sent"),
                    ("failed", "Failed (retryable)"),
                    ("skipped", "Skipped (consent / disabled)"),
                    ("dead_lettered", "Dead-lettered after retries"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
