# Generated by Django 5.1.6 on 2026-04-15 11:47

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("broadcast", "0005_initial"),
        ("contacts", "0007_initial"),
        ("sms", "0002_encrypt_credentials_add_dlr_index"),
        ("team_inbox", "0004_initial"),
        ("tenants", "0016_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RCSApp",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("GOOGLE_RBM", "Google RBM"), ("META_RCS", "Meta RCS")],
                        default="GOOGLE_RBM",
                        max_length=20,
                    ),
                ),
                (
                    "provider_credentials",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, help_text="Provider credentials stored as an encrypted JSON string.", null=True
                    ),
                ),
                ("agent_id", models.CharField(help_text="Google RBM agent ID or Meta phone number ID", max_length=100)),
                ("agent_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("daily_limit", models.IntegerField(default=10000)),
                ("messages_sent_today", models.IntegerField(default=0)),
                ("webhook_url", models.URLField(blank=True, max_length=512)),
                ("webhook_client_token", models.CharField(blank=True, max_length=64, unique=True)),
                ("sms_fallback_enabled", models.BooleanField(default=True)),
                ("price_per_message", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("price_per_rich_message", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sms_fallback_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rcs_fallback_apps",
                        to="sms.smsapp",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rcs_apps", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "RCS App",
                "verbose_name_plural": "RCS Apps",
                "unique_together": {("tenant", "provider", "agent_id")},
            },
        ),
        migrations.CreateModel(
            name="RCSOutboundMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("to_phone", models.CharField(max_length=20)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("RICH_CARD", "Rich Card"),
                            ("CAROUSEL", "Carousel"),
                            ("MEDIA", "Media"),
                            ("LOCATION", "Location"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                ("message_content", models.JSONField(blank=True, null=True)),
                ("suggestions", models.JSONField(blank=True, null=True)),
                ("provider_message_id", models.CharField(blank=True, db_index=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                (
                    "traffic_type",
                    models.CharField(
                        choices=[
                            ("TRANSACTION", "Transactional"),
                            ("PROMOTION", "Promotional"),
                            ("AUTHENTICATION", "Authentication"),
                            ("SERVICEREQUEST", "Service Request"),
                        ],
                        default="TRANSACTION",
                        max_length=30,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=30)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broadcast_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rcs_outbound_messages",
                        to="broadcast.broadcastmessage",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rcs_messages",
                        to="contacts.tenantcontact",
                    ),
                ),
                (
                    "fallback_sms_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rcs_fallback_messages",
                        to="sms.smsoutboundmessage",
                    ),
                ),
                (
                    "inbox_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rcs_outbound_messages",
                        to="team_inbox.messages",
                    ),
                ),
                (
                    "rcs_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="outbound_messages", to="rcs.rcsapp"
                    ),
                ),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RCSWebhookEvent",
            fields=[
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "Message"),
                            ("SUGGESTION_RESPONSE", "Suggestion Response"),
                            ("LOCATION", "Location"),
                            ("FILE", "File"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("IS_TYPING", "Is Typing"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=30,
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("GOOGLE_RBM", "Google RBM"), ("META_RCS", "Meta RCS")], max_length=20),
                ),
                ("sender_phone", models.CharField(blank=True, max_length=20)),
                ("provider_message_id", models.CharField(blank=True, max_length=120)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "rcs_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="webhook_events", to="rcs.rcsapp"
                    ),
                ),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["rcs_app", "provider_message_id"], name="rcs_rcswebh_rcs_app_88e053_idx"),
                    models.Index(fields=["is_processed", "created_at"], name="rcs_rcswebh_is_proc_e89fa2_idx"),
                ],
                "unique_together": {("rcs_app", "provider_message_id", "event_type")},
            },
        ),
    ]
