# Generated by Django 5.1.6 on 2026-04-15 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rcs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rcsoutboundmessage",
            old_name="fallback_sms_id",
            new_name="fallback_sms",
        ),
    ]
