# Generated by Django 5.1.15 on 2026-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rcs", "0003_rcstemplate_rcstemplatecard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rcstemplate",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("RICH_CARD", "Rich Card"),
                    ("CAROUSEL", "Carousel"),
                    ("MEDIA", "Media"),
                    ("LOCATION", "Location"),
                ],
                default="TEXT",
                max_length=20,
            ),
        ),
    ]
