# Generated by Django 5.2.16 on 2026-09-09 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaintenanceWindow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField()),
                (
                    "reason",
                    models.CharField(help_text="What the window was for, as reported to the partner.", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Maintenance window",
                "verbose_name_plural": "Maintenance windows",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("target", models.CharField(choices=[("api", "API"), ("ui", "Web UI")], max_length=8)),
                ("total_checks", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("failed_checks", models.PositiveIntegerField(default=0)),
                (
                    "probe_interval_seconds",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Interval between probes. A failed check is counted as this much downtime.",
                    ),
                ),
                (
                    "source",
                    models.CharField(default="grafana", help_text="Which monitor reported this.", max_length=32),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily availability",
                "verbose_name_plural": "Daily availability",
                "ordering": ["-date", "target"],
                "constraints": [
                    models.UniqueConstraint(fields=("date", "target"), name="unique_daily_availability_per_target"),
                    models.CheckConstraint(
                        condition=models.Q(("failed_checks__lte", models.F("total_checks"))),
                        name="failed_checks_not_greater_than_total",
                    ),
                ],
            },
        ),
    ]
