# Generated by Django 5.1.6 on 2026-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crmconnection",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crmconnection",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="crmentitymapping",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crmentitymapping",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="crmsyncevent",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crmsyncevent",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="crmconnection",
            name="provider",
            field=models.CharField(
                choices=[("hubspot", "HubSpot"), ("salesforce", "Salesforce"), ("generic_webhook", "Generic webhook")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="crmsyncevent",
            name="direction",
            field=models.CharField(
                choices=[("outbound", "Outbound (Jina → CRM)"), ("inbound", "Inbound (CRM → Jina)")], max_length=10
            ),
        ),
    ]
