from django.core.exceptions import ValidationError
from django.db import models

from abstract.managers import BaseTenantModelForFilterUserManager
from abstract.models import BaseModel, BaseTenantModelForFilterUser
from chat_flow.node_registry import validate_flow_for_platform
from jina_connect.platform_choices import PlatformChoices
from tenants.models import Tenant
from wa.models import WATemplate


class ChatFlow(BaseTenantModelForFilterUser):
    """
    Represents a complete conversational flow/decision tree for WhatsApp chatbots.

    A ChatFlow is the main container that defines an entire conversation experience,
    built from approved Gupshup WhatsApp templates with interactive buttons. Think of it
    as a "conversation script" that guides users through different paths based on their choices.

    Key Concepts:
    - Each flow represents one complete conversation journey (e.g., "Pizza Ordering", "Customer Support")
    - Flows are built visually using ReactFlow (drag-and-drop interface)
    - Each flow must start with an approved WhatsApp template that has buttons
    - Users navigate through the flow by clicking buttons, which trigger transitions to other messages
    - Flows are tenant-specific (each organization has their own isolated flows)

    Real-world Example:
        "Customer Support Flow":
        1. Start: "How can we help? [Sales] [Support] [Billing]"
        2. If user clicks "Support" → "What's your issue? [Technical] [Account] [Other]"
        3. If user clicks "Technical" → "Please describe your technical issue..."

    Data Structure:
        The flow_data field stores the complete ReactFlow JSON structure from the frontend,
        including node positions, connections, and configuration. This allows the visual
        editor to recreate the exact flow design.

    Usage:
        - Admins design flows using a visual drag-and-drop interface
        - System validates that all referenced templates are approved
        - Users interact with flows through WhatsApp bot conversations
        - Analytics track user behavior and flow performance

    Related Models:
        - ChatFlowNode: Individual messages/steps in the flow
        - ChatFlowEdge: Connections between messages (button click → next message)
        - UserChatFlowSession: Tracks where each user currently is in the flow
        - WATemplate: The actual WhatsApp message templates used in nodes
    """

    filter_by_user_tenant_fk = "tenant__tenant_users__user"
    tenant = models.ForeignKey(
        Tenant,
        on_delete=models.CASCADE,
        related_name="chat_flows",
        blank=True,
        null=True,
        help_text="The tenant/organization that owns this chat flow",
    )
    # ReactFlow JSON structure from frontend
    flow_data = models.JSONField(
        help_text="""
        Complete ReactFlow JSON structure containing the visual flow design.

        Expected Structure:
        {
            "nodes": [
                {
                    "id": "welcome-node",
                    "type": "template",
                    "position": {"x": 100, "y": 100},
                    "data": {
                        "template_id": 123,
                        "label": "Welcome Message",
                        "buttons": [...]
                    }
                }
            ],
            "edges": [
                {
                    "id": "edge-1",
                    "source": "welcome-node",
                    "target": "menu-node",
                    "data": {
                        "button_id": "btn-get-started",
                        "button_text": "Get Started"
                    }
                }
            ],
            "viewport": {"x": 0, "y": 0, "zoom": 1}
        }

        This JSON is generated by the ReactFlow visual editor and contains all the information
        needed to recreate the flow design, including node positions, connections, and styling.
        """
    )

    # Entry point - which template starts the flow
    start_template = models.ForeignKey(
        WATemplate,
        on_delete=models.CASCADE,
        related_name="flows_as_start",
        null=True,
        blank=True,
        limit_choices_to={"status": "APPROVED", "buttons__isnull": False},
        help_text="""
        The WhatsApp template that users will see first when they start this flow.

        Requirements:
        - Must be an APPROVED template (not pending or rejected)
        - Must have at least one button (flows require user interaction)
        - Must belong to the same tenant as this flow
        - Can be null for draft/inactive flows that are still being designed

        Example:
        If start_template is "Welcome Message" with buttons ["Get Started", "More Info"],
        then users will see this message first and can click either button to proceed.

        The start_template determines the first node that users land on when beginning
        a new chat flow session.
        """,
    )

    is_active = models.BooleanField(default=True, help_text="Whether this flow is active and can accept new sessions")

    # Which platform this flow runs on. Existing flows default to WhatsApp
    # for back-compat; voice and future channels set their own value. Used
    # by ``clean()`` to validate ``flow_data`` against the node-type
    # registry (see ``chat_flow.node_registry``).
    #
    # Non-WhatsApp flows leave ``start_template`` null and declare their
    # entry point via ``flow_data["entry_node_id"]``.
    platform = models.CharField(
        max_length=20,
        choices=PlatformChoices.choices,
        default=PlatformChoices.WHATSAPP,
        help_text="Platform this flow targets. Determines which node types are valid.",
    )

    class Meta:
        verbose_name = "Chat Flow"
        verbose_name_plural = "Chat Flows"

    def __str__(self):
        return f"{self.pk}"

    def clean(self):
        super().clean()
        errors = validate_flow_for_platform(self.flow_data, self.platform)
        if errors:
            raise ValidationError({"flow_data": errors})

    def save(self, *args, **kwargs):
        # ``full_clean`` runs field validators + our ``clean()`` so a flow
        # with incompatible nodes never reaches the database.
        self.full_clean()
        super().save(*args, **kwargs)


class ChatFlowNode(BaseModel):
    """
    Represents a single message/step within a ChatFlow conversation.

    Each ChatFlowNode corresponds to one WhatsApp message that users will see during
    their journey through a ChatFlow. Think of nodes as "conversation steps" or "screens"
    in the chat experience.

    Key Concepts:
    - Each node is linked to an approved WATemplate (the actual WhatsApp message)
    - Nodes have visual positions for the ReactFlow editor (drag-and-drop interface)
    - Nodes can contain additional configuration like custom button layouts
    - Users move between nodes by clicking buttons (handled by ChatFlowEdge)

    Node Types:
    - "template": Standard message node (most common)
    - "condition": Logic node for branching (future feature)
    - "action": Action node for integrations (future feature)

    Real-world Example:
        Node: "pizza-menu-node"
        Template: "Choose your pizza: {{1}}" with example "Choose your pizza: Margherita, Pepperoni"
        Buttons: ["Margherita", "Pepperoni", "Vegetarian"]
        Position: (400, 200) in the visual flow editor

    Data Flow:
        1. User reaches this node in their conversation
        2. System sends the linked template message to WhatsApp
        3. User sees the message and available buttons
        4. User clicks a button
        5. System uses ChatFlowEdge to determine next node
        6. Process repeats until conversation ends

    Visual Editor Integration:
        The position_x and position_y fields store where this node appears in the
        visual flow editor, allowing designers to create clean, organized flow diagrams.

    Template vs Node Data:
        - template: References the approved WhatsApp message content
        - node_data: Contains flow-specific overrides and button configurations

        This separation allows the same template to be used in multiple flows with
        different button configurations or additional metadata.
    """

    flow = models.ForeignKey(
        ChatFlow, on_delete=models.CASCADE, related_name="nodes", help_text="The ChatFlow that this node belongs to"
    )

    # ReactFlow node identification and configuration
    node_id = models.CharField(
        max_length=255,
        help_text="""
        Unique identifier for this node within the ReactFlow visual editor.

        Examples: "welcome-node", "pizza-menu", "payment-options"

        This ID is used to:
        - Reference nodes in the ReactFlow JSON structure
        - Connect nodes with edges in the visual editor
        - Debug and trace user paths through flows

        Must be unique within the flow.
        """,
    )
    node_type = models.CharField(
        max_length=50,
        default="template",
        help_text="""
        Type of node determining its behavior in the flow.

        Available Types:
        - "template": Standard message node that displays a WhatsApp template
        - "condition": Logic node for conditional branching (future feature)
        - "action": Integration node for external API calls (future feature)

        Currently, most nodes are "template" type since they represent WhatsApp messages.
        """,
    )

    # Template reference - the actual WhatsApp message content
    template = models.ForeignKey(
        WATemplate,
        on_delete=models.CASCADE,
        limit_choices_to={"status": "APPROVED"},
        blank=True,
        null=True,
        help_text="""
        The approved WhatsApp template that will be sent when users reach this node.

        Requirements:
        - Must be APPROVED status (Gupshup has validated the template)
        - Should belong to the same tenant as the flow
        - Template content cannot be modified once approved

        The template contains:
        - Message text (e.g., "Welcome to our store!")
        - Button definitions (text, types, actions)
        - Media attachments (images, documents, etc.)
        - Template metadata (category, language, etc.)

        Example Template:
        Content: "Your order status: {{1}}. What would you like to do?"
        Buttons: ["Track Order", "Cancel Order", "Contact Support"]
        """,
    )

    # Visual positioning in ReactFlow editor
    position_x = models.FloatField(
        help_text="""
        X coordinate of this node in the ReactFlow visual editor.

        Used for:
        - Saving and restoring visual flow layouts
        - Organizing flows in a readable manner
        - Maintaining designer's intended flow structure

        Coordinate system starts at (0,0) in the top-left corner.
        """
    )
    position_y = models.FloatField(
        help_text="""
        Y coordinate of this node in the ReactFlow visual editor.

        Used for:
        - Saving and restoring visual flow layouts
        - Creating logical top-to-bottom flow progression
        - Grouping related nodes visually

        Coordinate system starts at (0,0) in the top-left corner.
        """
    )

    # Node-specific configuration and overrides
    node_data = models.JSONField(
        default=dict,
        help_text="""
        Additional configuration data specific to this node within the flow context.

        Common Use Cases:
        1. Button overrides - Customize button layout for this specific flow
        2. Display labels - Human-readable names for the visual editor
        3. Conditional logic - Parameters for future conditional nodes
        4. Analytics tags - Custom tracking labels for this node

        Example Structure:
        {
            "label": "Pizza Selection",
            "buttons": [
                {
                    "id": "btn-margherita",
                    "text": "Margherita",
                    "type": "QUICK_REPLY",
                    "template_button_index": 0
                }
            ],
            "analytics_tags": ["menu", "pizza"],
            "display_priority": 1
        }

        Key Benefits:
        - Allows same template to behave differently in different flows
        - Enables flow-specific customizations without modifying templates
        - Supports visual editor metadata that doesn't belong in templates
        - Future-proofs for advanced node features
        """,
    )

    filter_by_user_tenant_fk = "flow__tenant__tenant_users__user"
    objects = BaseTenantModelForFilterUserManager()

    class Meta:
        verbose_name = "Chat Flow Node"
        verbose_name_plural = "Chat Flow Nodes"
        unique_together = ("flow", "node_id")

    def __str__(self):
        return f"{self.flow.name} - {self.node_id}"


class ChatFlowEdge(BaseModel):
    """
    Represents a connection/transition between two nodes in a ChatFlow.

    ChatFlowEdges define how users move through a conversation by mapping button clicks
    to the next message they should see. Think of edges as "conversation rules" that
    determine the flow of dialogue.

    Core Concept:
    When a user is at Node A and clicks a specific button, the edge tells the system
    which Node B to show next. This creates the interactive, branching conversation flow.

    Real-world Example:
        Source Node: "Welcome! How can we help?"
        Buttons: ["Order Pizza", "Track Order", "Contact Support"]

        Edge 1: "Order Pizza" button → Pizza Menu Node
        Edge 2: "Track Order" button → Order Status Node
        Edge 3: "Contact Support" button → Support Form Node

    Button Mapping Approaches:
    1. Legacy: button_text matching (e.g., "Order Pizza")
    2. Modern: button_id matching (e.g., "btn-order-pizza")

    The modern approach is preferred because:
    - More reliable than text matching
    - Supports internationalization (same button_id, different languages)
    - Prevents errors from typos in button text
    - Enables better debugging and analytics

    Edge Validation:
    - Source and target nodes must exist in the same flow
    - Referenced button must exist in the source node's template
    - Button type must be compatible with the edge behavior

    User Journey Tracking:
    Edges are crucial for analytics because they represent user choices.
    Each edge traversal indicates a user decision point and helps measure
    conversion rates through different conversation paths.

    Technical Implementation:
    When a user clicks a button in WhatsApp:
    1. System receives button click event
    2. Finds active UserChatFlowSession for the user
    3. Looks up ChatFlowEdge from current node with matching button
    4. Advances user to the target node
    5. Sends the new node's template message
    6. Updates analytics and session state
    """

    flow = models.ForeignKey(
        ChatFlow, on_delete=models.CASCADE, related_name="edges", help_text="The ChatFlow that this edge belongs to"
    )

    # ReactFlow edge identification
    edge_id = models.CharField(
        max_length=255,
        help_text="""
        Unique identifier for this edge within the ReactFlow visual editor.

        Examples: "welcome-to-menu", "payment-to-confirmation", "edge-1"

        Used for:
        - Visual editor state management
        - Debugging conversation flows
        - Maintaining edge references in ReactFlow JSON

        Must be unique within the flow.
        """,
    )

    # Connection definition - where users come from and go to
    source_node = models.ForeignKey(
        ChatFlowNode,
        on_delete=models.CASCADE,
        related_name="outgoing_edges",
        help_text="""
        The node that users are leaving when they click the button.

        This is the "current" node where the user sees a message and buttons.
        When they click a button, this edge defines where they go next.

        Example: User is viewing "Pizza Menu" node and clicks "Add to Cart"
        → source_node = "Pizza Menu" node
        """,
    )
    target_node = models.ForeignKey(
        ChatFlowNode,
        on_delete=models.CASCADE,
        related_name="incoming_edges",
        help_text="""
        The node that users will see after clicking the button.

        This is the "destination" node that becomes the user's new current position.

        Example: User clicks "Add to Cart" button
        → target_node = "Shopping Cart" node

        The user's session will be updated to show them at the target_node,
        and they'll receive the target node's template message.
        """,
    )

    # Button mapping - which button triggers this transition
    button_text = models.CharField(
        max_length=255,
        help_text="""
        The exact text of the button that triggers this edge transition.

        IMPORTANT: This must match the button text in the source node's template exactly.

        Examples: "Order Pizza", "Contact Support", "Yes, Continue"

        Button Matching Process:
        1. User clicks button in WhatsApp
        2. System receives button text from WhatsApp API
        3. System finds edge where button_text matches the clicked text
        4. System transitions user to target_node

        Legacy vs Modern Approach:
        - Legacy: Uses button_text for matching (this field)
        - Modern: Uses button_id from edge_data (more reliable)

        Both approaches are supported for backward compatibility.
        """,
    )
    button_type = models.CharField(
        max_length=50,
        help_text="""
        The type of button that triggers this transition.

        WhatsApp Button Types:
        - "QUICK_REPLY": Simple text button (most common)
        - "URL": Button that opens a website
        - "PHONE_NUMBER": Button that initiates a phone call
        - "OTP": Button for OTP/authentication flows

        This field helps with:
        - Validation during flow creation
        - Analytics and reporting
        - Future button-type-specific behaviors

        Must match the button type defined in the source template.
        """,
    )

    # Advanced edge configuration
    edge_data = models.JSONField(
        default=dict,
        help_text="""
        Additional configuration and metadata for this edge transition.

        Modern Structure (Recommended):
        {
            "button_id": "btn-order-pizza",        // Unique button identifier
            "button_text": "Order Pizza",          // Fallback text matching
            "button_type": "QUICK_REPLY",          // Button type
            "analytics_label": "main_cta",         // Custom analytics tag
            "conditions": {                        // Future: conditional logic
                "user_type": "premium"
            },
            "delay_seconds": 2                     // Future: delayed responses
        }

        Key Features:
        1. button_id: Modern, reliable button identification
        2. Analytics: Custom labels for tracking specific user paths
        3. Conditions: Future support for conditional edges
        4. Timing: Future support for delayed message delivery

        Migration Path:
        - Legacy edges use only button_text matching
        - Modern edges prefer button_id with button_text fallback
        - Both approaches work simultaneously for compatibility

        Benefits of button_id:
        - Survives template text changes
        - Supports multiple languages
        - Prevents typo-related bugs
        - Enables better debugging
        """,
    )

    filter_by_user_tenant_fk = "flow__tenant__tenant_users__user"
    objects = BaseTenantModelForFilterUserManager()

    class Meta:
        verbose_name = "Chat Flow Edge"
        verbose_name_plural = "Chat Flow Edges"
        unique_together = ("flow", "edge_id")

    def __str__(self):
        return f"{self.flow.name} - {self.source_node.node_id} -> {self.target_node.node_id} ({self.button_text})"


class UserChatFlowSession(BaseModel):
    """
    Tracks a user's (contact's) current position in a ChatFlow.

    When a contact starts interacting with a ChatFlow, a session is created to track:
    - Which flow they're in
    - Which node they're currently at
    - When they started and when the session ended

    This enables the system to:
    1. Resume conversations where the user left off
    2. Route incoming button clicks to the correct next node
    3. Track analytics on user journeys through flows

    Lifecycle:
    1. Contact triggers flow start → Session created with current_node = start node
    2. Template sent to contact
    3. Contact clicks button → Session.current_node updated to next node
    4. Repeat until end node reached or session expires
    5. Session marked as completed (is_active=False)

    One Active Session Per Contact Per Flow:
    A contact can only have ONE active session per flow at a time.
    Starting a new session in the same flow will deactivate the old one.
    """

    # Tenant for direct filtering (denormalized from flow.tenant)
    tenant = models.ForeignKey(
        Tenant,
        on_delete=models.CASCADE,
        related_name="chatflow_sessions",
        null=True,
        blank=True,
        help_text="The tenant this session belongs to (populated from flow.tenant)",
    )

    # Which contact is going through the flow
    contact = models.ForeignKey(
        "contacts.TenantContact",
        on_delete=models.CASCADE,
        related_name="chatflow_sessions",
        help_text="The contact going through this flow",
    )

    # Which flow they're in
    flow = models.ForeignKey(
        ChatFlow, on_delete=models.CASCADE, related_name="sessions", help_text="The ChatFlow being executed"
    )

    # Current position in the flow (node_id string, not FK)
    current_node_id = models.CharField(
        max_length=255,
        help_text="""
        The node_id of the node the contact is currently at.

        This is the string node_id (e.g., 'welcome-node'), not the database ID.
        After each step, this is updated to reflect where the user is.
        """,
    )

    # Session status
    is_active = models.BooleanField(default=True, help_text="Whether this session is still active (user can continue)")

    is_complete = models.BooleanField(
        default=False, help_text="Whether the user reached an end node (flow completed successfully)"
    )

    # Timestamps
    started_at = models.DateTimeField(auto_now_add=True, help_text="When the session started")

    ended_at = models.DateTimeField(null=True, blank=True, help_text="When the session ended (completed or expired)")

    # Optional: Store additional context/variables
    context_data = models.JSONField(
        default=dict, blank=True, help_text="Additional context data collected during the flow"
    )

    cancellation_reason = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text="Reason session was ended prematurely (e.g., 'Flow deactivated for editing')",
    )

    class Meta:
        verbose_name = "User Chat Flow Session"
        verbose_name_plural = "User Chat Flow Sessions"
        # Ensure we can query active sessions efficiently
        indexes = [
            models.Index(fields=["contact", "flow", "is_active"]),
            models.Index(fields=["is_active", "started_at"]),
        ]

    def __str__(self):
        status = "active" if self.is_active else ("complete" if self.is_complete else "ended")
        return f"Session {self.pk} - Contact {self.contact_id} in Flow {self.flow_id} ({status})"
