# Generated by Django 5.1.15 on 2026-05-15 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice", "0003_voice_sms_fallback_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recordingconsent",
            new_name="voice_recor_tenant__a286dc_idx",
            old_name="voice_recor_tenant__idx",
        ),
        migrations.RenameIndex(
            model_name="voicecall",
            new_name="voice_voice_tenant__ff1ef9_idx",
            old_name="voice_voice_tenant__b9d4e2_idx",
        ),
        migrations.RenameIndex(
            model_name="voicecall",
            new_name="voice_voice_tenant__bc97cc_idx",
            old_name="voice_voice_tenant__e7f1a3_idx",
        ),
        migrations.RenameIndex(
            model_name="voicecallevent",
            new_name="voice_voice_call_id_0703da_idx",
            old_name="voice_voice_call_id_c0a8d1_idx",
        ),
        migrations.RenameIndex(
            model_name="voiceproviderconfig",
            new_name="voice_voice_tenant__8c828a_idx",
            old_name="voice_voice_tenant__1d2c14_idx",
        ),
        migrations.RenameIndex(
            model_name="voiceproviderconfig",
            new_name="voice_voice_tenant__873114_idx",
            old_name="voice_voice_tenant__a3b5c4_idx",
        ),
        migrations.RenameIndex(
            model_name="voiceratecard",
            new_name="voice_voice_provide_715efe_idx",
            old_name="voice_voice_provide_aa11bb_idx",
        ),
        migrations.RenameIndex(
            model_name="voicerecording",
            new_name="voice_voice_call_id_aa3e48_idx",
            old_name="voice_voice_call_id_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="voicerecording",
            new_name="voice_voice_retenti_dcbe07_idx",
            old_name="voice_voice_retent_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="voicetemplate",
            new_name="voice_voice_tenant__00a880_idx",
            old_name="voice_voice_tenant__d1e2f3_idx",
        ),
        migrations.AlterField(
            model_name="recordingconsent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recordingconsent",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
