# Generated by Django 5.1.6 on 2026-02-09 14:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("broadcast", "0002_initial"),
        ("contacts", "0002_initial"),
        ("tenants", "0003_tenantwaapp_bsp_credentials_tenantwaapp_daily_limit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WABroadcast",
            fields=[],
            options={
                "verbose_name": "WA Broadcast",
                "verbose_name_plural": "WA Broadcasts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("broadcast.broadcast",),
        ),
        migrations.CreateModel(
            name="WAContacts",
            fields=[],
            options={
                "verbose_name": "WA Contact",
                "verbose_name_plural": "WA Contacts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("contacts.tenantcontact",),
        ),
        migrations.CreateModel(
            name="WASubscription",
            fields=[
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("webhook_url", models.URLField()),
                ("event_types", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("bsp_subscription_id", models.CharField(blank=True, max_length=255, null=True)),
                ("verify_token", models.CharField(blank=True, max_length=255, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wa_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="tenants.tenantwaapp",
                    ),
                ),
            ],
            options={
                "verbose_name": "WA Subscription",
                "verbose_name_plural": "WA Subscriptions",
                "db_table": "wa_subscription_v2",
            },
        ),
        migrations.CreateModel(
            name="WATemplate",
            fields=[
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("content", models.TextField(blank=True, help_text="Template content", null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "element_name",
                    models.CharField(help_text="Unique template name (lowercase, underscores)", max_length=255),
                ),
                (
                    "language_code",
                    models.CharField(default="en", help_text="Template language (e.g., en, en_US)", max_length=20),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATION", "Authentication"),
                            ("MARKETING", "Marketing"),
                            ("UTILITY", "Utility"),
                        ],
                        default="MARKETING",
                        max_length=20,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("DOCUMENT", "Document"),
                            ("LOCATION", "Location"),
                            ("AUDIO", "Audio"),
                            ("CAROUSEL", "Carousel"),
                            ("CATALOG", "Catalog"),
                            ("PRODUCT", "Product"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PAUSED", "Paused"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("header", models.TextField(blank=True, help_text="Header text (optional)", null=True)),
                ("footer", models.TextField(blank=True, help_text="Footer text (max 60 chars)", null=True)),
                ("buttons", models.JSONField(blank=True, help_text="Array of button objects", null=True)),
                (
                    "example_body",
                    models.JSONField(blank=True, help_text="Example values for body placeholders", null=True),
                ),
                (
                    "example_header",
                    models.JSONField(blank=True, help_text="Example values for header placeholders", null=True),
                ),
                (
                    "media_handle",
                    models.CharField(blank=True, help_text="META media handle ID", max_length=255, null=True),
                ),
                (
                    "example_media_url",
                    models.URLField(blank=True, help_text="Example media URL for approval", null=True),
                ),
                ("cards", models.JSONField(blank=True, help_text="Carousel card objects", null=True)),
                ("meta_template_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("bsp_template_id", models.CharField(blank=True, max_length=255, null=True)),
                ("placeholder_mapping", models.JSONField(blank=True, null=True)),
                ("vertical", models.CharField(default="OTHER", help_text="Business vertical", max_length=100)),
                ("is_lto", models.BooleanField(default=False, help_text="Limited Time Offer template")),
                ("lto_text", models.CharField(blank=True, max_length=255, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("needs_sync", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tag", models.ManyToManyField(related_name="template_tags", to="tenants.tenanttags")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wa_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="templates", to="tenants.tenantwaapp"
                    ),
                ),
            ],
            options={
                "verbose_name": "WA Template",
                "verbose_name_plural": "WA Templates",
                "db_table": "wa_template_v2",
            },
        ),
        migrations.CreateModel(
            name="WAMessage",
            fields=[
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("wa_message_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                (
                    "direction",
                    models.CharField(choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound")], max_length=10),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("TEMPLATE", "Template"),
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("DOCUMENT", "Document"),
                            ("AUDIO", "Audio"),
                            ("LOCATION", "Location"),
                            ("CONTACTS", "Contacts"),
                            ("STICKER", "Sticker"),
                            ("INTERACTIVE", "Interactive"),
                            ("REACTION", "Reaction"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("template_params", models.JSONField(blank=True, null=True)),
                (
                    "media_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="META media ID (from upload or webhook)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "media_url",
                    models.URLField(blank=True, help_text="Media download URL (expires after 5 min)", null=True),
                ),
                ("media_mime_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "media_sha256",
                    models.CharField(blank=True, help_text="SHA-256 hash of the media file", max_length=64, null=True),
                ),
                ("media_file_size", models.BigIntegerField(blank=True, help_text="File size in bytes", null=True)),
                ("media_caption", models.TextField(blank=True, null=True)),
                ("media_filename", models.CharField(blank=True, max_length=255, null=True)),
                ("button_payload", models.CharField(blank=True, max_length=255, null=True)),
                ("button_text", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("location_name", models.CharField(blank=True, max_length=255, null=True)),
                ("location_address", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("is_billable", models.BooleanField(default=True)),
                ("cost", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("conversation_type", models.CharField(blank=True, max_length=50, null=True)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_messages",
                        to="contacts.tenantcontact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wa_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="tenants.tenantwaapp"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="wa.watemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "WA Message",
                "verbose_name_plural": "WA Messages",
                "db_table": "wa_message_v2",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WAMedia",
            fields=[
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "meta_media_id",
                    models.CharField(
                        db_index=True,
                        help_text="Media ID returned by META upload or received in webhook",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        blank=True,
                        help_text="Phone Number ID that uploaded/received this media",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("mime_type", models.CharField(help_text="MIME type (e.g., image/jpeg, video/mp4)", max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AUDIO", "Audio"),
                            ("DOCUMENT", "Document"),
                            ("IMAGE", "Image"),
                            ("STICKER", "Sticker"),
                            ("VIDEO", "Video"),
                        ],
                        help_text="WhatsApp media category",
                        max_length=20,
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, help_text="File size in bytes", null=True)),
                (
                    "sha256",
                    models.CharField(blank=True, help_text="SHA-256 hash of the file", max_length=64, null=True),
                ),
                ("filename", models.CharField(blank=True, help_text="Original filename", max_length=255, null=True)),
                ("cached_url", models.URLField(blank=True, help_text="Cached media URL (valid ~5 min)", null=True)),
                (
                    "url_fetched_at",
                    models.DateTimeField(blank=True, help_text="When the cached URL was last fetched", null=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("UPLOAD", "Uploaded via API"), ("WEBHOOK", "Received via webhook")],
                        default="UPLOAD",
                        max_length=10,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the media ID expires (30 days for upload, 7 days for webhook)",
                        null=True,
                    ),
                ),
                ("is_expired", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wa_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="tenants.tenantwaapp",
                    ),
                ),
                (
                    "used_in_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Message this media is attached to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_assets",
                        to="wa.wamessage",
                    ),
                ),
                (
                    "used_in_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this media is used as header handle",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_assets",
                        to="wa.watemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "WA Media",
                "verbose_name_plural": "WA Media",
                "db_table": "wa_media_v2",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WAWebhookEvent",
            fields=[
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "Message"),
                            ("STATUS", "Status"),
                            ("TEMPLATE", "Template"),
                            ("BILLING", "Billing"),
                            ("ACCOUNT", "Account"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bsp",
                    models.CharField(
                        choices=[
                            ("GUPSHUP", "Gupshup"),
                            ("META", "Meta"),
                            ("TWILIO", "Twilio"),
                            ("MESSAGEBIRD", "MessageBird"),
                            ("WATI", "WATI"),
                            ("AISENSY", "Aisensy"),
                            ("INTERAKT", "Interakt"),
                            ("YELLOW_AI", "Yellow.ai"),
                        ],
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="wa.wamessage",
                    ),
                ),
                (
                    "wa_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="tenants.tenantwaapp",
                    ),
                ),
            ],
            options={
                "verbose_name": "WA Webhook Event",
                "verbose_name_plural": "WA Webhook Events",
                "db_table": "wa_webhook_event_v2",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="watemplate",
            index=models.Index(fields=["status", "needs_sync"], name="wa_template_status_f7c397_idx"),
        ),
        migrations.AddIndex(
            model_name="watemplate",
            index=models.Index(fields=["wa_app", "status"], name="wa_template_wa_app__7bd137_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="watemplate",
            unique_together={("wa_app", "element_name", "language_code")},
        ),
        migrations.AddIndex(
            model_name="wamessage",
            index=models.Index(fields=["wa_app", "contact", "-created_at"], name="wa_message__wa_app__c47f4e_idx"),
        ),
        migrations.AddIndex(
            model_name="wamessage",
            index=models.Index(fields=["wa_message_id"], name="wa_message__wa_mess_b62c40_idx"),
        ),
        migrations.AddIndex(
            model_name="wamessage",
            index=models.Index(fields=["status", "direction"], name="wa_message__status_96d40c_idx"),
        ),
        migrations.AddIndex(
            model_name="wamedia",
            index=models.Index(fields=["wa_app", "category", "-created_at"], name="wa_media_v2_wa_app__03264c_idx"),
        ),
        migrations.AddIndex(
            model_name="wamedia",
            index=models.Index(fields=["source", "is_expired"], name="wa_media_v2_source_3f4bc4_idx"),
        ),
        migrations.AddIndex(
            model_name="wawebhookevent",
            index=models.Index(fields=["is_processed", "event_type"], name="wa_webhook__is_proc_c7eecd_idx"),
        ),
        migrations.AddIndex(
            model_name="wawebhookevent",
            index=models.Index(fields=["wa_app", "event_type", "-created_at"], name="wa_webhook__wa_app__e674c6_idx"),
        ),
    ]
