# Generated by Django 5.1.6 on 2026-02-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_templates', '0001_initial'),
        ('wa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watemplate',
            name='number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gupshup_template', to='message_templates.templatenumber'),
        ),
    ]
