# Generated by Django 5.1.6 on 2026-02-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wa", "0005_increase_example_media_url_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="wamessage",
            name="gs_message_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Secondary message ID — stores the Gupshup UUID (messageId) when wa_message_id holds the Cloud API wamid, or vice-versa.",
                max_length=255,
                null=True,
            ),
        ),
    ]
