# Generated by Django 5.1.6 on 2026-02-27 12:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_tenantcontact_dnc_tenantcontact_last_called_at_and_more"),
        ("tenants", "0014_add_payment_config_to_tenant_wa_app"),
        ("wa", "0010_backfill_template_numbers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="wawebhookevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("MESSAGE", "Message"),
                    ("STATUS", "Status"),
                    ("TEMPLATE", "Template"),
                    ("BILLING", "Billing"),
                    ("ACCOUNT", "Account"),
                    ("PAYMENT", "Payment"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WAOrder",
            fields=[
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "reference_id",
                    models.CharField(db_index=True, help_text="Unique per tenant. Alphanumeric + _ . -", max_length=35),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("digital-goods", "Digital Goods"), ("physical-goods", "Physical Goods")],
                        default="physical-goods",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("total_amount", models.PositiveBigIntegerField(default=0)),
                ("subtotal", models.PositiveBigIntegerField(default=0)),
                ("tax", models.PositiveBigIntegerField(default=0)),
                ("shipping", models.PositiveBigIntegerField(default=0)),
                ("discount", models.PositiveBigIntegerField(default=0)),
                ("items", models.JSONField(blank=True, default=list)),
                ("payment_gateway", models.CharField(blank=True, default="", max_length=20)),
                ("configuration_name", models.CharField(blank=True, default="", max_length=60)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("partially_shipped", "Partially Shipped"),
                            ("shipped", "Shipped"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("pending", "Pending"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refund_pending", "Refund Pending"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=255, null=True)),
                ("pg_transaction_id", models.CharField(blank=True, max_length=255, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "order_details_payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full order_details action.parameters snapshot."
                    ),
                ),
                ("payment_captured_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_orders",
                        to="contacts.tenantcontact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_status_messages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="All order_status WAMessages sent for this order.",
                        related_name="order_status_updates",
                        to="wa.wamessage",
                    ),
                ),
                (
                    "outgoing_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="The order_details WAMessage that created this order.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_from_message",
                        to="wa.wamessage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wa_orders", to="tenants.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wa_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="tenants.tenantwaapp"
                    ),
                ),
            ],
            options={
                "db_table": "wa_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WAPaymentEvent",
            fields=[
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=30)),
                ("transaction_id", models.CharField(blank=True, max_length=255, null=True)),
                ("pg_transaction_id", models.CharField(blank=True, max_length=255, null=True)),
                ("transaction_status", models.CharField(blank=True, max_length=30, null=True)),
                ("amount_value", models.PositiveBigIntegerField(default=0)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payment_events", to="wa.waorder"
                    ),
                ),
                (
                    "webhook_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_events",
                        to="wa.wawebhookevent",
                    ),
                ),
            ],
            options={
                "db_table": "wa_payment_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="waorder",
            index=models.Index(fields=["tenant", "payment_status"], name="idx_wa_order_payment"),
        ),
        migrations.AddIndex(
            model_name="waorder",
            index=models.Index(fields=["tenant", "order_status"], name="idx_wa_order_status"),
        ),
        migrations.AddConstraint(
            model_name="waorder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reference_id"), name="uq_wa_order_tenant_reference_id"
            ),
        ),
    ]
