# Generated by Django 5.1.6 on 2026-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wa", "0012_increase_media_url_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wawebhookevent",
            name="bsp",
            field=models.CharField(
                choices=[
                    ("GUPSHUP", "Gupshup"),
                    ("META", "Meta"),
                    ("TWILIO", "Twilio"),
                    ("MESSAGEBIRD", "MessageBird"),
                    ("WATI", "WATI"),
                    ("AISENSY", "Aisensy"),
                    ("INTERAKT", "Interakt"),
                    ("YELLOW_AI", "Yellow.ai"),
                    ("GOOGLE_RBM", "Google RBM"),
                    ("META_RCS", "Meta RCS"),
                ],
                max_length=20,
            ),
        ),
    ]
