# Generated by Django 5.1.6 on 2026-04-17 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message_templates", "0001_initial"),
        ("tenants", "0016_initial"),
        ("wa", "0013_alter_wawebhookevent_bsp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="watemplate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="watemplate",
            name="platform",
            field=models.CharField(
                choices=[("WHATSAPP", "WhatsApp"), ("SMS", "SMS"), ("TELEGRAM", "Telegram"), ("RCS", "RCS")],
                db_index=True,
                default="WHATSAPP",
                help_text="Channel this template belongs to.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="watemplate",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant owning this template (set for non-WA templates).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_templates",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="watemplate",
            name="wa_app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="tenants.tenantwaapp",
            ),
        ),
        migrations.AddIndex(
            model_name="watemplate",
            index=models.Index(fields=["platform", "tenant"], name="wa_template_platfor_dcf135_idx"),
        ),
        migrations.AddConstraint(
            model_name="watemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("wa_app__isnull", False)),
                fields=("wa_app", "element_name", "language_code"),
                name="unique_wa_app_element_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="watemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("wa_app__isnull", True)),
                fields=("tenant", "platform", "element_name", "language_code"),
                name="unique_tenant_platform_element_lang",
            ),
        ),
    ]
