# Generated by Django 5.1.15 on 2026-04-17 11:12

from django.db import migrations


def backfill_tenant(apps, schema_editor):
    """Set tenant from wa_app.tenant for WATemplates that have wa_app but no tenant."""
    from django.db.models import OuterRef, Subquery

    WATemplate = apps.get_model("wa", "WATemplate")
    TenantWAApp = apps.get_model("tenants", "TenantWAApp")

    WATemplate.objects.filter(tenant__isnull=True, wa_app__isnull=False).update(
        tenant=Subquery(TenantWAApp.objects.filter(pk=OuterRef("wa_app_id")).values("tenant_id")[:1])
    )


class Migration(migrations.Migration):
    dependencies = [
        ("wa", "0014_alter_watemplate_unique_together_watemplate_platform_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
    ]
