# Generated by Django 5.1.6 on 2026-05-19 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0010_add_import_to_contact_source"),
        ("ctwa", "0002_rename_ctwa_campaign_tenant_status_ctwa_ctwaca_tenant__87dd43_idx_and_more"),
        ("tenants", "0019_rbac_add_voice_permissions"),
        ("wa", "0017_waconversation_ctwa_lead_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="waconversation",
            new_name="wa_waconver_wa_app__07c3cd_idx",
            old_name="wa_conv_app_contact_last_idx",
        ),
        migrations.AddField(
            model_name="waconversation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="waconversation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waconversation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="waconversation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="waconversation",
            name="wa_app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="tenants.tenantwaapp"
            ),
        ),
        migrations.AddIndex(
            model_name="waconversation",
            index=models.Index(fields=["service_window_expires_at"], name="wa_waconver_service_e79523_idx"),
        ),
    ]
