# Generated by Django 5.1.6 on 2026-05-20 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0010_add_import_to_contact_source"),
        ("ctwa", "0004_alter_ctwalead_crm_external_id"),
        ("tenants", "0019_rbac_add_voice_permissions"),
        ("wa", "0018_rename_wa_conv_app_contact_last_idx_wa_waconver_wa_app__07c3cd_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="waconversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True)),
                fields=("wa_app", "contact"),
                name="waconversation_unique_open_per_app_contact",
            ),
        ),
    ]
