# Generated by Django 5.2.16 on 2026-09-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa', '0019_waconversation_waconversation_unique_open_per_app_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='watemplate',
            name='quality_rating',
            field=models.CharField(blank=True, choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('UNKNOWN', 'Unknown')], help_text='Latest quality score reported by META for this template.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='watemplate',
            name='quality_rating_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
