"""Per-app ``hub.verify_token`` validation (#307).

A BSP will not deliver to a callback URL it has not verified, and it verifies one
by sending ``GET ?hub.mode=subscribe&hub.verify_token=…&hub.challenge=…`` and
requiring the challenge back. The receiver used to measure that token against a
single deployment-wide setting::

    expected_token = getattr(django_settings, "META_WEBHOOK_VERIFY_TOKEN", "")

With one platform-owned app that is fine. With #305's bring-your-own-app handover
it means every client has to be handed the *same* value — a secret shared across
tenants, and enough for any one holder to complete the handshake for another
client's endpoint and have a BSP start delivering that client's traffic
wherever they like.

So the token moves onto the app, and the test that matters is the one that could
not be written before: **app A's token fails on app B's URL.** A file asserting
only that the right token still works would pass against the old code too.

What is pinned here:

* an app's own token completes the handshake on its own URL, and on no other's;
* the deployment-wide token no longer completes a handshake on a per-app URL —
  the fallback's absence *is* the ticket, since a fallback would leave the shared
  secret sufficient everywhere;
* a mismatch is 403, is counted per app, and neither the presented token nor the
  expected one reaches a log sink;
* the legacy unsuffixed path still checks the deployment-wide setting, because it
  is the URL registered in live dashboards (#310) and has no app to ask;
* the token is generated by this deployment with a CSPRNG, is never equal between
  two apps, and cannot be chosen or overwritten through the API;
* the setup screen and the receiver agree: the token the endpoint hands a client
  is the one their URL will actually accept, which is what
  ``verify_token_scope == "app"`` is a promise about;
* Gupshup gets all of the above from the same code path, not from a second
  implementation (#305 D-4).

HOW TO RUN:
    DB_NAME=jc307 python -m pytest wa/tests/test_per_app_verify_token.py -v
"""

from __future__ import annotations

import itertools
import json
import logging
import uuid

import pytest
from django.contrib.auth import get_user_model
from django.db import connection
from django.urls import reverse
from rest_framework.test import APIClient

from tenants.models import BSPChoices, generate_wa_webhook_verify_token
from wa.services import webhook_identity

LEGACY_META_URL = "/wa/v2/webhooks/meta/"
LEGACY_GUPSHUP_URL = "/wa/v2/webhooks/gupshup/"

CHALLENGE = "1158201444"
DEPLOYMENT_META_TOKEN = "deployment-wide-meta-token"  # noqa: S105 — a fixture, not a credential
DEPLOYMENT_GUPSHUP_TOKEN = "deployment-wide-gupshup-token"  # noqa: S105 — a fixture, not a credential

User = get_user_model()

_user_seq = itertools.count(1)

pytestmark = pytest.mark.django_db


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────


def _tenant(prefix: str = "VerifyTokenTenant"):
    from tenants.models import Tenant

    return Tenant.objects.create(name=f"{prefix}-{uuid.uuid4().hex[:8]}", is_active=True)


def _wa_app(tenant=None, **overrides):
    from wa.models import WAApp

    fields = {
        "tenant": tenant or _tenant(),
        "app_name": f"app-{uuid.uuid4().hex[:6]}",
        "app_id": f"gs-{uuid.uuid4().hex[:8]}",
        "app_secret": "s",  # noqa: S106 — Gupshup column, unrelated to this file
        "wa_number": f"+1{uuid.uuid4().int % 10**10:010d}",
        "waba_id": f"waba-{uuid.uuid4().hex[:8]}",
        "phone_number_id": f"pn-{uuid.uuid4().hex[:8]}",
        "bsp": BSPChoices.META,
        "is_active": True,
    }
    fields.update(overrides)
    return WAApp.objects.create(**fields)


def _url(wa_app, bsp=BSPChoices.META) -> str:
    name = "wa:meta-webhook-app" if bsp == BSPChoices.META else "wa:gupshup-webhook-app"
    return reverse(name, kwargs={"webhook_identifier": wa_app.webhook_identifier})


def _handshake(client, url, token, challenge=CHALLENGE):
    query = {"hub.mode": "subscribe", "hub.challenge": challenge}
    if token is not None:
        query["hub.verify_token"] = token
    return client.get(url, query)


def _api_client_for(tenant, role_slug: str = "owner") -> APIClient:
    """An APIClient authenticated as a user holding *role_slug* in *tenant*.

    Same helper as ``test_webhook_app_identity._api_client_for``; the setup
    endpoint is permission-gated, so there is no reading its payload without one.
    """
    from tenants.models import TenantRole, TenantUser

    role = TenantRole.objects.get(tenant=tenant, slug=role_slug)
    suffix = next(_user_seq)
    user = User.objects.create_user(
        username=f"vtok_{role_slug}_{uuid.uuid4().hex[:8]}",
        email=f"vtok_{uuid.uuid4().hex[:8]}@test.com",
        mobile=f"+9190002{suffix:05d}",
        password="testpass123",  # noqa: S106 — throwaway test login
    )
    TenantUser.objects.create(tenant=tenant, user=user, role=role)

    api = APIClient()
    api.force_authenticate(user=user)
    return api


class _Capture(logging.Handler):
    """Collects formatted records, the way a real handler would write them.

    ``caplog`` alone is not enough: the project's LOGGING config gives the ``wa``
    logger ``propagate=False``, so its records never reach the root handler
    pytest attaches. Same helper as
    ``test_gupshup_webhook_verification._Capture``.
    """

    def __init__(self):
        super().__init__(level=logging.DEBUG)
        self.lines: list[str] = []

    def emit(self, record):
        self.lines.append(self.format(record))

    @property
    def text(self) -> str:
        return "\n".join(self.lines)


def _capture_wa_logs():
    handler = _Capture()
    handler.setFormatter(logging.Formatter("[{levelname}] {name}: {message}", style="{"))
    logger = logging.getLogger("wa")
    logger.addHandler(handler)
    return handler, logger


# ─────────────────────────────────────────────────────────────────────────────
# The property the old code could not have: one app's token is one app's token
# ─────────────────────────────────────────────────────────────────────────────


def test_an_apps_own_token_completes_the_handshake_on_its_own_url(client, settings):
    settings.META_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_META_TOKEN
    app = _wa_app()

    response = _handshake(client, _url(app), app.webhook_verify_token)

    assert response.status_code == 200
    assert response.content.decode() == CHALLENGE
    assert response["Content-Type"].startswith("text/plain")


def test_app_as_token_does_not_complete_app_bs_handshake(client, settings):
    """The acceptance criterion, and the whole reason the column exists.

    Two clients, two apps, two URLs. Before #307 both endpoints measured the
    presented token against one setting, so either client's token — and anyone
    else's copy of it — completed the handshake for the other's endpoint.
    """
    settings.META_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_META_TOKEN
    app_a = _wa_app()
    app_b = _wa_app()

    assert app_a.webhook_verify_token != app_b.webhook_verify_token

    crossed = _handshake(client, _url(app_b), app_a.webhook_verify_token)

    assert crossed.status_code == 403
    assert CHALLENGE not in crossed.content.decode()
    assert crossed.json() == {"error": "Verify token mismatch"}

    # ...and each app's own token still works on its own URL, so the rejection
    # above is about whose token it is and not about the handshake being broken.
    assert _handshake(client, _url(app_a), app_a.webhook_verify_token).status_code == 200
    assert _handshake(client, _url(app_b), app_b.webhook_verify_token).status_code == 200


def test_the_deployment_wide_token_does_not_complete_a_per_app_handshake(client, settings):
    """No fallback on a per-app URL, and the absence is the point.

    A second chance at the shared setting would leave every holder of it able to
    complete every client's handshake, which is the cross-tenant secret #307
    removes. An app with a token of its own accepts exactly that token.
    """
    settings.META_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_META_TOKEN
    app = _wa_app()

    response = _handshake(client, _url(app), DEPLOYMENT_META_TOKEN)

    assert response.status_code == 403
    assert CHALLENGE not in response.content.decode()


def test_an_app_without_a_token_of_its_own_still_falls_back_to_the_setting(client, settings):
    """The pre-#307 configuration keeps working.

    The column is blank until ``tenants/0031`` fills it, and a fixture or a row
    written around ``save()`` can still be blank afterwards. Such an app must not
    have an unverifiable URL — it has the handshake it had before.
    """
    from wa.models import WAApp

    settings.META_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_META_TOKEN
    app = _wa_app()
    WAApp.objects.filter(pk=app.pk).update(webhook_verify_token="")
    app.refresh_from_db()
    assert app.webhook_verify_token == ""

    assert _handshake(client, _url(app), DEPLOYMENT_META_TOKEN).status_code == 200
    assert _handshake(client, _url(app), "something-else").status_code == 403


def test_a_stored_token_is_compared_stripped(client, settings):
    """A value that reached the column with whitespace still verifies.

    Same failure mode ``select_app_secret`` strips for: a token compared as
    ``"<token>\\n"`` refuses every genuine handshake, which looks exactly like a
    client pasting the wrong value and is nearly impossible to diagnose from
    outside.
    """
    from wa.models import WAApp

    settings.META_WEBHOOK_VERIFY_TOKEN = ""
    app = _wa_app()
    token = app.webhook_verify_token
    WAApp.objects.filter(pk=app.pk).update(webhook_verify_token=f"  {token}\n")

    assert _handshake(client, _url(app), token).status_code == 200


# ─────────────────────────────────────────────────────────────────────────────
# A refused handshake: 403, counted, and silent about the token
# ─────────────────────────────────────────────────────────────────────────────


def test_a_mismatch_is_counted_against_the_app_whose_url_was_addressed(client, settings):
    """Counted because nothing else would notice (#307).

    A client re-verifying with a stale token and someone guessing at a live one
    look the same from here; both are worth seeing. The bucket is per app so the
    count says whose endpoint is being refused.
    """
    settings.META_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_META_TOKEN
    app = _wa_app()
    bystander = _wa_app()

    # Deltas, not absolutes: the counters are shared Redis keys bucketed by UTC
    # day, and clearing the cache here would be a FLUSHDB of every other
    # process's keys too (see ``test_webhook_app_identity``).
    before = webhook_identity.verify_token_rejections(BSPChoices.META, wa_app=app)
    before_bystander = webhook_identity.verify_token_rejections(BSPChoices.META, wa_app=bystander)

    _handshake(client, _url(app), "wrong-token")
    _handshake(client, _url(app), "wrong-token-again")

    assert webhook_identity.verify_token_rejections(BSPChoices.META, wa_app=app) == before + 2
    assert webhook_identity.verify_token_rejections(BSPChoices.META, wa_app=bystander) == before_bystander
    # A successful handshake is not a rejection.
    _handshake(client, _url(app), app.webhook_verify_token)
    assert webhook_identity.verify_token_rejections(BSPChoices.META, wa_app=app) == before + 2


def test_a_legacy_path_mismatch_is_counted_too(client, settings):
    """The unsuffixed receiver has no app to attribute a refusal to, and is
    counted in its own bucket rather than not at all."""
    settings.META_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_META_TOKEN

    before = webhook_identity.verify_token_rejections(BSPChoices.META)

    assert _handshake(client, LEGACY_META_URL, "wrong-token").status_code == 403

    assert webhook_identity.verify_token_rejections(BSPChoices.META) == before + 1


def test_neither_the_presented_nor_the_expected_token_reaches_the_logs(client, settings):
    """A presented token is a guess at a secret — or another tenant's real token
    sent to the wrong endpoint. Either way a log sink is a wider audience than
    its owner agreed to, and ``got=%s`` used to put it there."""
    settings.META_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_META_TOKEN
    app = _wa_app()
    other = _wa_app()
    presented = other.webhook_verify_token

    handler, logger = _capture_wa_logs()
    try:
        response = _handshake(client, _url(app), presented)
    finally:
        logger.removeHandler(handler)

    assert response.status_code == 403

    output = handler.text
    assert presented not in output
    assert app.webhook_verify_token not in output
    assert DEPLOYMENT_META_TOKEN not in output
    # Silence is not the fix: the refusal is still reported, with the app it was
    # refused for and the scope of the token it was measured against.
    assert "mismatch" in output.lower()
    assert str(app.pk) in output
    assert "token_scope=app" in output


def test_a_successful_handshake_does_not_log_the_token_either(client, settings):
    settings.META_WEBHOOK_VERIFY_TOKEN = ""
    app = _wa_app()

    handler, logger = _capture_wa_logs()
    try:
        response = _handshake(client, _url(app), app.webhook_verify_token)
    finally:
        logger.removeHandler(handler)

    assert response.status_code == 200
    assert app.webhook_verify_token not in handler.text


# ─────────────────────────────────────────────────────────────────────────────
# The legacy path, unchanged
# ─────────────────────────────────────────────────────────────────────────────


def test_the_legacy_path_still_checks_the_deployment_wide_token(client, settings):
    """Registered in live dashboards, and it has no app to ask for a token of
    its own: during a handshake there is no body to route from."""
    settings.META_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_META_TOKEN
    _wa_app()  # an app with its own token exists and changes nothing here

    assert _handshake(client, LEGACY_META_URL, DEPLOYMENT_META_TOKEN).status_code == 200
    assert _handshake(client, LEGACY_META_URL, "wrong-token").status_code == 403


def test_an_apps_own_token_does_not_complete_the_legacy_handshake(client, settings):
    """The legacy path is single-app by construction: one deployment-wide token,
    which is not any particular client's."""
    settings.META_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_META_TOKEN
    app = _wa_app()

    assert _handshake(client, LEGACY_META_URL, app.webhook_verify_token).status_code == 403


def test_with_nothing_configured_anywhere_the_check_is_still_skipped(client, settings):
    """Unchanged behaviour, asserted so it cannot change by accident.

    "No token configured means no check" is what both handshakes have always
    done, and the two must not drift apart (#308). After #307 that state needs
    both halves empty.
    """
    from wa.models import WAApp

    settings.META_WEBHOOK_VERIFY_TOKEN = ""
    settings.GUPSHUP_WEBHOOK_VERIFY_TOKEN = ""
    app = _wa_app()
    WAApp.objects.filter(pk=app.pk).update(webhook_verify_token="")

    assert _handshake(client, LEGACY_META_URL, "anything-at-all").status_code == 200
    assert _handshake(client, _url(app), "anything-at-all").status_code == 200


# ─────────────────────────────────────────────────────────────────────────────
# Gupshup, through the same code path
# ─────────────────────────────────────────────────────────────────────────────


def test_the_gupshup_handshake_is_per_app_as_well(client, settings):
    """Per-app identity is defined for every BSP (#305 D-4). A Meta-only version
    of this would have to be undone when Embedded Signup lands beside
    bring-your-own-app."""
    settings.GUPSHUP_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_GUPSHUP_TOKEN
    app = _wa_app(bsp=BSPChoices.GUPSHUP)
    other = _wa_app(bsp=BSPChoices.GUPSHUP)

    url = _url(app, bsp=BSPChoices.GUPSHUP)

    assert _handshake(client, url, app.webhook_verify_token).status_code == 200
    assert _handshake(client, url, other.webhook_verify_token).status_code == 403
    assert _handshake(client, url, DEPLOYMENT_GUPSHUP_TOKEN).status_code == 403
    # The legacy Gupshup path is untouched, exactly as META's is.
    assert _handshake(client, LEGACY_GUPSHUP_URL, DEPLOYMENT_GUPSHUP_TOKEN).status_code == 200


def test_a_gupshup_mismatch_is_counted_under_its_own_bsp(client, settings):
    settings.GUPSHUP_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_GUPSHUP_TOKEN
    app = _wa_app(bsp=BSPChoices.GUPSHUP)

    before_gupshup = webhook_identity.verify_token_rejections(BSPChoices.GUPSHUP, wa_app=app)
    before_meta = webhook_identity.verify_token_rejections(BSPChoices.META, wa_app=app)

    _handshake(client, _url(app, bsp=BSPChoices.GUPSHUP), "wrong-token")

    assert webhook_identity.verify_token_rejections(BSPChoices.GUPSHUP, wa_app=app) == before_gupshup + 1
    assert webhook_identity.verify_token_rejections(BSPChoices.META, wa_app=app) == before_meta


# ─────────────────────────────────────────────────────────────────────────────
# How the token is produced, and who may choose it
# ─────────────────────────────────────────────────────────────────────────────


def test_every_app_is_issued_its_own_token_at_creation():
    tokens = {_wa_app().webhook_verify_token for _ in range(5)}

    assert len(tokens) == 5, "two apps were issued the same handshake token"
    assert all(token for token in tokens)


def test_the_token_carries_at_least_128_bits_from_a_csprng(monkeypatch):
    """#307's bar. ``secrets.token_urlsafe(24)`` is ~192 bits; the assertion is
    on the floor, not the exact length, so raising it is not a test change."""
    import secrets as secrets_module

    tokens = {generate_wa_webhook_verify_token() for _ in range(200)}
    assert len(tokens) == 200

    random_part = next(iter(tokens)).removeprefix("whv_")
    # base64url: 6 bits per character. 22 characters is 132 bits.
    assert len(random_part) >= 22, f"{len(random_part) * 6} bits is below the 128 #307 asks for"

    # From the CSPRNG, not from ``random``: which module produced a value is the
    # one thing a reimplementation could get wrong invisibly, because a weak
    # token looks exactly like a strong one.
    called = {"n": 0}
    real = secrets_module.token_urlsafe

    def counting(*args, **kwargs):
        called["n"] += 1
        return real(*args, **kwargs)

    monkeypatch.setattr(secrets_module, "token_urlsafe", counting)
    generate_wa_webhook_verify_token()

    assert called["n"] == 1, "the token is not coming from secrets.token_urlsafe"


def test_the_comparison_is_constant_time():
    """``==`` on a secret leaks its shared prefix through timing, and this
    endpoint will take as many guesses as anyone cares to send it.

    Asserted by reading the source because a timing assertion is not something a
    test suite on shared CI can make honestly: the difference is microseconds and
    the noise is milliseconds. ``_verify_meta_signature`` already compares its
    HMAC this way (#306) — the handshake is the same kind of comparison.
    """
    import inspect

    from wa.views import _tokens_match

    source = inspect.getsource(_tokens_match)
    assert "compare_digest" in source, "the verify-token comparison is no longer constant-time"


def test_the_migration_gives_each_existing_row_its_own_token():
    """``tenants/0031``'s backfill, driven directly.

    ``AddField`` evaluates a callable default *once* for the rows that already
    exist, so the obvious one-step migration would hand every app on the instance
    the same token — the defect being removed, reintroduced by the migration that
    removes it. The column is also encrypted, so a bulk ``update`` of one literal
    would be wrong twice. This runs the real data function over rows that really
    are blank.
    """
    import importlib

    from django.apps import apps as django_apps

    from wa.models import WAApp

    migration = importlib.import_module("tenants.migrations.0031_wa_app_webhook_verify_token")

    apps = [_wa_app(), _wa_app(), _wa_app()]
    WAApp.objects.filter(pk__in=[app.pk for app in apps]).update(webhook_verify_token="")

    migration.fill_webhook_verify_tokens(django_apps, None)

    tokens = [WAApp.objects.get(pk=app.pk).webhook_verify_token for app in apps]
    assert all(tokens), "a row was left without a token"
    assert len(set(tokens)) == len(tokens), "two rows were given the same token"
    # And written through the field's encryption, not as a plaintext literal. The
    # ORM cannot show the difference — a value that fails to decrypt is handed
    # back verbatim, so every assertion above passes either way — so the stored
    # bytes are read directly.
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT webhook_verify_token FROM tenants_tenantwaapp WHERE id = %s",
            [apps[0].pk],
        )
        stored = cursor.fetchone()[0]

    assert stored != tokens[0], "the handshake token is sitting in the column in plaintext"


def test_a_client_cannot_choose_its_own_token_through_the_api(settings):
    """Issued, never chosen — a client-supplied token could be weak, reused, or
    another tenant's. Both app-writing endpoints are checked, because a guard on
    one would be a signpost to the other."""
    tenant = _tenant()
    app = _wa_app(tenant)
    issued = app.webhook_verify_token
    api = _api_client_for(tenant)

    v2 = api.patch(
        f"/wa/v2/apps/{app.pk}/",
        {"webhook_verify_token": "chosen-by-the-client"},
        format="json",
    )
    assert v2.status_code in (200, 400), v2.data
    app.refresh_from_db()
    assert app.webhook_verify_token == issued

    legacy = api.patch(
        f"/tenants/tenant-gupshup/{app.app_id}/",
        {"webhook_verify_token": "chosen-by-the-client"},
        format="json",
    )
    assert legacy.status_code in (200, 400, 403), getattr(legacy, "data", legacy)
    app.refresh_from_db()
    assert app.webhook_verify_token == issued


def test_the_token_is_not_published_by_the_ordinary_app_payloads(settings):
    """It leaves through the ``wa_app.manage``-gated setup endpoint or not at
    all. ``list``/``retrieve`` on both app endpoints need only ``wa_app.view``,
    and that is the line #310 drew for the callback URL."""
    tenant = _tenant()
    app = _wa_app(tenant)
    api = _api_client_for(tenant)

    responses = [
        api.get("/wa/v2/apps/"),
        api.get(f"/wa/v2/apps/{app.pk}/"),
        api.get("/tenants/tenant-gupshup/"),
        api.get(f"/tenants/tenant-gupshup/{app.app_id}/"),
    ]

    for response in responses:
        assert response.status_code == 200, response.request["PATH_INFO"]
        assert app.webhook_verify_token not in json.dumps(response.data, default=str)


# ─────────────────────────────────────────────────────────────────────────────
# The screen and the receiver cannot disagree
# ─────────────────────────────────────────────────────────────────────────────


def test_the_token_the_setup_endpoint_hands_over_is_the_one_the_url_accepts(client, settings):
    """The contract behind ``verify_token_scope == "app"``.

    A screen reporting an app-scoped token that the handshake ignores reads as
    working until the day it matters, so this takes the token straight out of the
    response and completes a real handshake with it.
    """
    settings.DEFAULT_WEBHOOK_BASE_URL = "https://hooks.example.test"
    settings.META_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_META_TOKEN

    tenant = _tenant()
    app = _wa_app(tenant)
    api = _api_client_for(tenant)

    body = api.get(f"/wa/v2/apps/{app.pk}/webhook-setup/").data
    assert body["verify_token_scope"] == "app"

    path = body["callback_url"].replace("https://hooks.example.test", "")
    response = _handshake(client, path, body["verify_token"])

    assert response.status_code == 200
    assert response.content.decode() == CHALLENGE


def test_the_scope_says_deployment_only_when_that_is_what_is_checked(settings):
    """The field is a statement about the receiver, not a label.

    ``"deployment"`` has to mean the handshake really does check the shared
    setting, which after #307 is true only for an app with no token of its own.
    """
    from wa.models import WAApp

    settings.META_WEBHOOK_VERIFY_TOKEN = DEPLOYMENT_META_TOKEN

    app = _wa_app()
    assert webhook_identity.verify_token(app) == (app.webhook_verify_token, "app")

    WAApp.objects.filter(pk=app.pk).update(webhook_verify_token="")
    app.refresh_from_db()
    assert webhook_identity.verify_token(app) == (DEPLOYMENT_META_TOKEN, "deployment")

    settings.META_WEBHOOK_VERIFY_TOKEN = ""
    assert webhook_identity.verify_token(app) == ("", "none")
