# Generated by Django 5.1.6 on 2026-04-13 10:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0005_tenantcontact_telegram_chat_id_and_more"),
        ("team_inbox", "0003_alter_messages_platform"),
        ("tenants", "0015_alter_tenantmedia_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramBotApp",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "bot_token",
                    models.CharField(
                        help_text="Telegram Bot API token (stored encrypted at rest via FIELD_ENCRYPTION_KEY).",
                        max_length=255,
                    ),
                ),
                ("bot_username", models.CharField(blank=True, help_text="Bot @username (without @)", max_length=255)),
                (
                    "bot_user_id",
                    models.BigIntegerField(blank=True, help_text="Telegram's numeric user ID for this bot", null=True),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Random secret for X-Telegram-Bot-Api-Secret-Token validation",
                        max_length=64,
                    ),
                ),
                ("webhook_url", models.URLField(blank=True, help_text="Auto-generated webhook URL", max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("daily_limit", models.IntegerField(default=1000, help_text="Daily message limit")),
                ("messages_sent_today", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="telegram_bots", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Bot App",
                "verbose_name_plural": "Telegram Bot Apps",
                "unique_together": {("tenant", "bot_user_id")},
            },
        ),
        migrations.CreateModel(
            name="TelegramOutboundMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("chat_id", models.BigIntegerField(help_text="Target Telegram chat ID")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("PHOTO", "Photo"),
                            ("DOCUMENT", "Document"),
                            ("VIDEO", "Video"),
                            ("AUDIO", "Audio"),
                            ("VOICE", "Voice"),
                            ("LOCATION", "Location"),
                            ("CONTACT", "Contact"),
                            ("CALLBACK_ANSWER", "Callback Answer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, help_text="What was sent to Telegram", null=True)),
                (
                    "provider_message_id",
                    models.BigIntegerField(blank=True, help_text="message_id from Telegram response", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_messages",
                        to="telegram.telegrambotapp",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_outbound",
                        to="contacts.tenantcontact",
                    ),
                ),
                (
                    "inbox_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to team inbox timeline entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_outbound",
                        to="team_inbox.messages",
                    ),
                ),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant")),
            ],
            options={
                "verbose_name": "Telegram Outbound Message",
                "verbose_name_plural": "Telegram Outbound Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TelegramWebhookEvent",
            fields=[
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("update_id", models.BigIntegerField(help_text="Telegram update_id")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "Message"),
                            ("CALLBACK_QUERY", "Callback Query"),
                            ("EDITED_MESSAGE", "Edited Message"),
                            ("INLINE_QUERY", "Inline Query"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=30,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "bot_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="telegram.telegrambotapp",
                    ),
                ),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant")),
            ],
            options={
                "verbose_name": "Telegram Webhook Event",
                "verbose_name_plural": "Telegram Webhook Events",
                "indexes": [
                    models.Index(fields=["bot_app", "update_id"], name="telegram_te_bot_app_f2691a_idx"),
                    models.Index(fields=["is_processed", "created_at"], name="telegram_te_is_proc_75048e_idx"),
                ],
                "unique_together": {("bot_app", "update_id")},
            },
        ),
    ]
