# Generated by Django 5.1.6 on 2026-04-13 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_tenantcontact_telegram_chat_id_and_more"),
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambotapp",
            name="webhook_secret",
            field=models.CharField(
                blank=True,
                help_text="Random secret for X-Telegram-Bot-Api-Secret-Token validation",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="telegramoutboundmessage",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_outbound",
                to="contacts.tenantcontact",
            ),
        ),
    ]
