# Generated by Django 5.1.6 on 2026-04-13 13:05

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0002_outbound_contact_nullable_webhook_secret_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambotapp",
            name="bot_token",
            field=encrypted_model_fields.fields.EncryptedCharField(
                help_text="Telegram Bot API token (encrypted at rest via FIELD_ENCRYPTION_KEY)."
            ),
        ),
    ]
