# Generated by Django 5.1.15 on 2026-04-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0005_outbound_sending_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramwebhookevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("MESSAGE", "Message"),
                    ("CALLBACK_QUERY", "Callback Query"),
                    ("EDITED_MESSAGE", "Edited Message"),
                    ("INLINE_QUERY", "Inline Query"),
                    ("MESSAGE_REACTION", "Message Reaction"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=30,
            ),
        ),
    ]
