# Generated by Django 5.1.6 on 2026-03-20 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0014_add_payment_config_to_tenant_wa_app"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("template_approved", "Template Approved"),
                            ("template_rejected", "Template Rejected"),
                            ("template_submitted", "Template Submitted"),
                            ("broadcast_scheduled", "Broadcast Scheduled"),
                            ("broadcast_completed", "Broadcast Completed"),
                            ("broadcast_failed", "Broadcast Failed"),
                            ("contact_added", "Contact Added"),
                            ("contact_imported", "Contacts Imported"),
                            ("automation_updated", "Automation Updated"),
                            ("automation_failed", "Automation Failed"),
                            ("wallet_recharged", "Wallet Recharged"),
                            ("low_balance", "Low Balance Warning"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="tenants.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "-created_at"], name="notificatio_tenant__3b20a7_idx"),
                    models.Index(fields=["tenant", "is_read", "-created_at"], name="notificatio_tenant__9a5521_idx"),
                ],
            },
        ),
    ]
